### ISSUE TITLE
Can you provide doc for feed hosting ?

### ISSUE THREAD

**Issue by moksy386** [OpenVisionE2/openvision-oe#11]
I have succefully compiled for DM520 and i have uploaded feed package to free host but I got error curl 8 with opkg update I think it's a manifest thing or I don't know cause I'm newbie.

Is there any advice or doc tutorial how to host feed packages ? Thank you

**Comment by persianpros** [comment]
You could read https://github.com/Hains/openvision-dm920-oe-core/blob/master/README.md for now but @Hains will create a topic for this in future.

**Comment by moksy386** [comment]
Thank you very much, unfortunately I didn't understand the "site.conf" part where it is ? and how to do since my feed url is 
dm520.ezyro.com/ipk

**Comment by persianpros** [comment]
If you're using "image.sh" and you did answer feed, you don't need that.

**Comment by moksy386** [comment]
But i Got error nuber 8 curl with opkg update with the sources above
