### ISSUE TITLE
ERROR: enigma2-sh4

### ISSUE THREAD

**Issue by sid8796** [OpenVisionE2/openvision-oe#14]
WARNING: libpam-1.3.0-r5 do_package_qa: QA Issue: ELF binary '/home/sid8796/openpli-oe-core/build/tmp/work/sh4-oe-linux/libpam/1.3.0-r5/packages-split/pam-plugin-timestamp/usr/sbin/pam_timestamp_check' has relocations in .text [textrel]
ERROR: enigma2-sh4+gitAUTOINC+1067381319-r0 do_patch: Command Error: 'quilt --quiltrc /home/sid8796/openpli-oe-core/build/tmp/work/hl101-oe-linux/enigma2/sh4+gitAUTOINC+1067381319-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch openvision.patch
patching file data/setup.xml
patching file lib/driver/hdmi_cec.cpp
Hunk #1 succeeded at 479 with fuzz 2 (offset -22 lines).
patching file lib/python/Components/AVSwitch.py
patching file lib/python/Components/Network.py
Hunk #1 FAILED at 423.
1 out of 2 hunks FAILED -- rejects in file lib/python/Components/Network.py
patching file lib/python/Components/NimManager.py
Hunk #1 succeeded at 1573 (offset -1 lines).
Hunk #2 succeeded at 1581 (offset -1 lines).
Hunk #3 succeeded at 1589 (offset -1 lines).
patching file lib/python/Components/Sources/FrontendStatus.py
patching file lib/python/Components/UsageConfig.py
Hunk #5 succeeded at 121 (offset 3 lines).
Hunk #6 succeeded at 138 (offset 3 lines).
Hunk #7 succeeded at 218 (offset 3 lines).
Hunk #8 succeeded at 287 (offset 4 lines).
patching file lib/service/servicedvb.cpp
Hunk #1 succeeded at 1742 (offset 5 lines).
Patch openvision.patch does not apply (enforce with -f)
ERROR: enigma2-sh4+gitAUTOINC+1067381319-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/sid8796/openpli-oe-core/build/tmp/work/hl101-oe-linux/enigma2/sh4+gitAUTOINC+1067381319-r0/temp/log.do_patch.1400
ERROR: Task (/home/sid8796/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3262 tasks of which 1917 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/sid8796/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_patch
Summary: There were 21 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
Makefile:125: recipe for target 'image' failed
make: *** [image] Error 1

**Comment by Hains** [comment]
Solved.

https://github.com/OpenVisionE2/enigma2-openpli-sh4/commits/develop

**Comment by BarviX6** [comment]
NOTE: recipe enigma2-sh4+gitAUTOINC+4377ef07f2-r0: task do_patch: Started
ERROR: enigma2-sh4+gitAUTOINC+4377ef07f2-r0 do_patch: Command Error: 'quilt --quiltrc /home/barvix/openpli-oe-core/build/tmp/work/spark-oe-linux/enigma2/sh4+gitAUTOINC+4377ef07f2-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch openvision.patch
patching file data/setup.xml
patching file lib/driver/hdmi_cec.cpp
Hunk #1 succeeded at 479 with fuzz 2 (offset -22 lines).
patching file lib/python/Components/AVSwitch.py
patching file lib/python/Components/Network.py
patching file lib/python/Components/NimManager.py
Hunk #1 succeeded at 1573 (offset -1 lines).
Hunk #2 succeeded at 1581 (offset -1 lines).
Hunk #3 succeeded at 1589 (offset -1 lines).
patching file lib/python/Components/Sources/FrontendStatus.py
patching file lib/python/Components/UsageConfig.py
Hunk #5 succeeded at 121 (offset 3 lines).
Hunk #6 succeeded at 138 (offset 3 lines).
Hunk #7 succeeded at 218 (offset 3 lines).
Hunk #8 succeeded at 287 (offset 4 lines).
patching file lib/service/servicedvb.cpp
Hunk #1 succeeded at 1742 (offset 5 lines).
patching file configure.ac
Hunk #1 succeeded at 72 (offset 26 lines).
patching file lib/python/Plugins/Extensions/MediaPlayer/settings.py
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- rejects in file lib/python/Plugins/Extensions/MediaPlayer/settings.py
patching file lib/python/Plugins/SystemPlugins/OSDPositionSetup/overscanwizard.py
patching file lib/python/Plugins/SystemPlugins/SoftwareManager/plugin.py
patching file lib/python/Screens/About.py
patching file lib/python/Screens/SoftwareUpdate.py
Patch openvision.patch does not apply (enforce with -f)
ERROR: enigma2-sh4+gitAUTOINC+4377ef07f2-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/barvix/openpli-oe-core/build/tmp/work/spark-oe-linux/enigma2/sh4+gitAUTOINC+4377ef07f2-r0/temp/log.do_patch.733
NOTE: recipe enigma2-sh4+gitAUTOINC+4377ef07f2-r0: task do_patch: Failed
ERROR: Task (/home/barvix/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3174 tasks of which 3138 didn't need to be rerun and 1 failed.

**Comment by BarviX6** [comment]
NOTE: recipe enigma2-sh4+gitAUTOINC+ee105c631a-r0: task do_patch: Started
NOTE: recipe enigma2-sh4+gitAUTOINC+ee105c631a-r0: task do_patch: Succeeded

**Comment by BarviX6** [comment]
ERROR: enigma2-sh4+gitAUTOINC+ee105c631a-r0 do_compile: Function failed: do_compile (log file is located at /home/barvix/openpli-oe-core/build/tmp/work/spark-oe-linux/enigma2/sh4+gitAUTOINC+ee105c631a-r0/temp/log.do_compile.12997
Makefile:1746: recipe for target 'driver/driver_libenigma_driver_a-hdmi_cec.o' failed
make[4]: *** [driver/driver_libenigma_driver_a-hdmi_cec.o] Error 1

**Comment by BarviX6** [comment]
include -fno-rtti -fno-exceptions -rdynamic -funwind-tables -pthread -fopenmp     -MT driver/driver_libenigma_driver_a-hdmi_cec.o -MD -MP -MF driver/.deps/driver_libenigma_driver_a-hdmi_cec.Tpo -c -o driver/driver_libenigma_driver_a-hdmi_cec.o `test -f 'driver/hdmi_cec.cpp' || echo '../../git/lib/'`driver/hdmi_cec.cpp
../../git/lib/driver/hdmi_cec.cpp: In member function 'long int eHdmiCEC::translateKey(unsigned char)':
../../git/lib/driver/hdmi_cec.cpp:482:3: error: duplicate case value
   case 0x4c:
   ^
../../git/lib/driver/hdmi_cec.cpp:446:3: error: previously used here
   case 0x4C:
   ^
../../git/lib/driver/hdmi_cec.cpp:485:3: error: duplicate case value
   case 0x4b:
   ^
../../git/lib/driver/hdmi_cec.cpp:443:3: error: previously used here
   case 0x4B:
   ^
Makefile:1746: recipe for target 'driver/driver_libenigma_driver_a-hdmi_cec.o' failed
make[4]: *** [driver/driver_libenigma_driver_a-hdmi_cec.o] Error 1

**Comment by Hains** [comment]
Update and try again.

**Comment by Hains** [comment]
Image Spark successful.
