### ISSUE TITLE
Mecool K1 Pro Enigma2 Crashes 

### ISSUE THREAD

**Issue by engineerkhan15** [OpenVisionE2/openvision-oe#15]
At last I was able to compile openvision enigma2 for my k1pro. After compiling, I prepared a bootable microsd card with the image and booted the device. It started booting with OpenVision logo but just after the logo, I saw the green crash screen. Tried to boot a number of times but every time same problem. Here is the crash log:
[https://www.mediafire.com/file/pg8p7jd8st6ztml/enigma2_crash.log/file](url)

**Comment by blueveryday** [comment]
yes , my k1 plus box also fail after burning the image.

**Comment by erbasandrade** [comment]
Can some friend make the image available for testing?
I can test it here and give you an answer!

**Comment by Hains** [comment]
Here you go.
Test image k1 pro
http://www.mediafire.com/file/fvg7euvwbsh3sae/openvision-enigma2-develop-7.0-r1-k1pro_sdcard.zip/file

**Comment by blueveryday** [comment]
> Here you go.
> Test image k1 pro
> http://www.mediafire.com/file/fvg7euvwbsh3sae/openvision-enigma2-develop-7.0-r1-k1pro_sdcard.zip/file

Sir ， Did you share with us that image of K1 plus (S905 CPU) ?
I compile it by myself , but not boot box .
Thank you very much.

**Comment by persianpros** [comment]
Don't waste your time on Mecool devices please, and please don't open new issues regarding these boxes, after Gamma changes in PLi's enigma2 it won't boot anymore (Revert didn't fix the problem and it only compiles) and even if it boots there will be no dvb support. (Scan works but you won't get any audio/video)

Just keep in mind the moment our build server starts to work I won't answer any question about self builing images as it only makes me tired and when there is a build server why should someone compile it again?
