### ISSUE TITLE
dm500hd feed :ERROR: No recipes available for

### ISSUE THREAD

**Issue by ycf83** [OpenVisionE2/openvision-oe#16]
![2018-12-31-194356_1574x520_scrot](https://user-images.githubusercontent.com/39797567/50566699-7857ef00-0d34-11e9-827b-a499b6a20d37.png)

**Comment by persianpros** [comment]
You need to update using update.sh

**Comment by persianpros** [comment]
image.sh will update each time you use it but to be sure first do update.sh then use image.sh
