### ISSUE TITLE
OpenVision Web Forum

### ISSUE THREAD

**Issue by budiarno** [OpenVisionE2/openvision-oe#17]
Hi guys.

I'm sorry to post here. But I need to know, where are you guys hang out now? Any new link to the web forum after the thread closed on OpenPLi web forum?

Kindest regards.
Budiarno

**Comment by Hains** [comment]
Hi.
We're working on an own forum at his moment.
When ready, we'll announce it.

**Comment by persianpros** [comment]
@Hains could you please compile an image for "vusolo" (normal and old version) so @mammadalius could test it?

**Comment by Hains** [comment]
Yes, but what do you mean with 'old version' exactly? Not openvision?

**Comment by Hains** [comment]
Build vusolo Open Vision running...

**Comment by persianpros** [comment]
I mean the box name: "vusolo" which is the first solo ;)

**Comment by Hains** [comment]
Yeah OK, when vusolo is finished, i start build vusolo4K.

**Comment by persianpros** [comment]
Ok please share that image with me :)

**Comment by Hains** [comment]
There it is. I had to remove the rtl8192cu wifi driver. It doesn't compile with vusolo.
http://www.mediafire.com/file/pnfj58nnwdlj5n7/openvision-develop-vusolo_usb.zip/file

Solo4K still running. 
Due to ARM arch almost from scratch, so be patience.

**Comment by Hains** [comment]
Solo4K
http://www.mediafire.com/file/q136xh5oz3ph84b/openvision-develop-vusolo4k_usb.zip/file

Happy new year.

**Comment by HFX1958** [comment]
Hi, Hains (Hans)  I hope you can make a image for the DM920

Happy new year for all testers en developpers

Regards Bigsat (HFX)

**Comment by Hains** [comment]
Test image dm920
http://www.mediafire.com/file/tfoulkzbgdgbvj4/openvision-enigma2-develop-dm920_web.zip/file

Image uses build server Zeros, so you can install plugins and get updates.

**Comment by Hains** [comment]
@jerrybutler1 

Build feed:
```
MACHINE=sf8008 make feed
```

Install Apache2 (Debian based distro's):
```
sudo apt install apache2
```

Create directories:
```
cd /var/www/html

sudo mkdir feeds;cd feeds;sudo mkdir openvision-develop;cd openvision-develop;
```

Create symlinks:
```
sudo ln -s /home/<your username>/openpli-oe-core/build/tmp/deploy/ipk/sf8008 sf8008 

sudo ln -s /home/<your username>/openpli-oe-core/build/tmp/deploy/ipk/all all

sudo ln -s /home/<your username>/openpli-oe-core/build/tmp/deploy/ipk/armv7ahf-neon armv7ahf-neon
```
Thus you need to create a symlink for each directory in the openpli-oe-core/build/tmp/deploy/ipk directory with the same name.
When you add a box to your build, you need to add (a) symlink(s).

At last.
Add the following line to the openpli-oe-core/site.conf file.
```
DISTRO_HOST = " <IP address of your build server> "
e.g.
DISTRO_HOST = "192.168.1.105"
```

**Comment by HFX1958** [comment]
Hi, Hains (Hans) i have send you a email (ftp not working dm920)

**Comment by jerrybutler1** [comment]
@Hains  thanks.

**Comment by ycf83** [comment]
hi, 
i made upgrade with telnet from terminal and with software update from menu, 
in about -> last upgrade ->  unknown  
always show unknown, it's nothing ... just for information :) 
thnk's for your hard work

**Comment by persianpros** [comment]
@Hains I noticed your compiled files don't have "7.0-r1" after https://github.com/OpenVisionE2/openvision-oe/commit/166bcebd167a3c18f55d68b1fdb68318029c21e0 maybe some metas hav their own version ...
