### ISSUE TITLE
iptv in dm800 not work

### ISSUE THREAD

**Issue by elhawaryna** [OpenVisionE2/openvision-oe#17]
Open Vision Enigma2 crash log

crashdate=Fri Nov 22 07:35:02 2019
compiledate=Nov 21 2019
skin=PLi-HD/skin.xml
sourcedate=2019-11-19
branch=develop
rev=efa4d6d
component=enigma2

stbmodel=dm800
stbbrand=dreambox
kernelcmdline=root=/dev/mtdblock3 rootfstype=jffs2 rw console=ttyS0,115200
nimsockets=NIM Socket 0:
visionversion=7.3
visionrevision=r60

<  4289.549> [eFixedMessagePump] write error Bad file descriptor

dmesg

] set wss 7 on display 1
<4>[4294820.413000] set sb to 3(1)
<4>[4294820.424000] disable wss on display 0
<4>[4294820.428000] set wss 7 on display 1
<4>[4294820.436000] set current avs auto aspect to 16:9
<4>[4294820.442000] disable wss on display 0
<4>[4294820.446000] set wss 7 on display 1
<4>[4294820.449000] set sb to 3(1)
<4>[4294820.483000] set current avs auto aspect to 16:9
<4>[4294820.488000] disable wss on display 0
<4>[4294820.492000] set wss 7 on display 1
<4>[4294820.495000] set sb to 3(1)
<4>[4294820.503000] set current avs auto aspect to 16:9
<4>[4294820.508000] disable wss on display 0
<4>[4294820.512000] set wss 7 on display 1
<4>[4294820.516000] set sb to 3(1)
<4>[4294820.525000] disable wss on display 0
<4>[4294820.529000] set wss 7 on display 1
<4>[4294820.537000] set current avs auto aspect to 16:9
<4>[4294820.543000] disable wss on display 0
<4>[4294820.547000] set wss 7 on display 1
<4>[4294820.551000] set sb to 3(1)
<4>[4294820.583000] set current avs auto aspect to 16:9
<4>[4294820.588000] disable wss on display 0
<4>[4294820.592000] set wss 7 on display 1
<4>[4294820.596000] set sb to 3(1)
<4>[4294820.604000] set current avs auto aspect to 16:9
<4>[4294820.609000] disable wss on display 0
<4>[4294820.613000] set wss 7 on display 1
<4>[4294820.616000] set sb to 3(1)
<4>[4294820.624000] disable wss on display 0
<4>[4294820.628000] set wss 7 on display 1
<4>[4294820.637000] set current avs auto aspect to 16:9
<4>[4294820.643000] disable wss on display 0
<4>[4294820.647000] set wss 7 on display 1
<4>[4294820.650000] set sb to 3(1)
<4>[4294820.685000] set current avs auto aspect to 16:9
<4>[4294820.690000] disable wss on display 0
<4>[4294820.694000] set wss 7 on display 1
<4>[4294820.698000] set sb to 3(1)
<4>[4294820.706000] set current avs auto aspect to 16:9
<4>[4294820.711000] disable wss on display 0
<4>[4294820.714000] set wss 7 on display 1
<4>[4294820.718000] set sb to 3(1)
<4>[4294820.725000] disable wss on display 0
<4>[4294820.729000] set wss 7 on display 1
<4>[4294820.738000] set current avs auto aspect to 16:9
<4>[4294820.744000] disable wss on display 0
<4>[4294820.748000] set wss 7 on display 1
<4>[4294820.752000] set sb to 3(1)
<4>[4294820.783000] set current avs auto aspect to 16:9
<4>[4294820.788000] disable wss on display 0
<4>[4294820.792000] set wss 7 on display 1
<4>[4294820.796000] set sb to 3(1)
<4>[4294820.804000] set current avs auto aspect to 16:9
<4>[4294820.809000] disable wss on display 0
<4>[4294820.813000] set wss 7 on display 1
<4>[4294820.817000] set sb to 3(1)
<4>[4294820.855000] set current avs auto aspect to 16:9
<4>[4294820.861000] disable wss on display 0
<4>[4294820.865000] set wss 7 on display 1
<4>[4294820.869000] set sb to 3(1)
<4>[4294820.875000] set current avs auto aspect to 16:9
<4>[4294820.881000] disable wss on display 0
<4>[4294820.885000] set wss 7 on display 1
<4>[4294820.889000] set sb to 3(1)
<4>[4294820.895000] disable wss on display 0
<4>[4294820.900000] set wss 7 on display 1
<4>[4294820.907000] set current avs auto aspect to 16:9
<4>[4294820.912000] disable wss on display 0
<4>[4294820.916000] set wss 7 on display 1
<4>[4294820.921000] set sb to 3(1)
<4>[4294820.940000] 781 ms: 85 
<4>[4294821.012000] 69 ms: 85 
<4>[4294821.025000] 10 ms: 85 
<4>[4294821.227000] 200 ms: 85 
<4>[4294823.911000] 2681 ms: 85 
<4>[4294824.161000] 247 ms: 88 
<4>[4294824.463000] 300 ms: 89 
<4>[4294827.872000] 3406 ms: 89 
<4>[4294828.988000] 1113 ms: 91 
<4>[4294835.434000] 6443 ms: 92 
<4>[4294835.628000] 191 ms: 99 
<4>[4294835.663000] 32 ms: 99 
<4>[4294835.670000] 4 ms: 99 
<4>[4294838.074000] alps_bsbe2 is in normal mode now
<4>[4294840.100000] pilot_off!
<4>[4294840.211000] start pcr0 on dmx 0 pid:a3 index 1
<4>[4294840.217000] start audio on dmx 0 pid:5c
<4>[4294840.222000] audio xpt start
<4>[4294840.225000] sync is off so we enable it
<4>[4294840.230000] demux-index 0 pcr0pid a3
<4>[4294840.233000] using 1 as pcr0 pidchannel
<4>[4294840.240000] AC3
<4>[4294840.242000] audio: streamtype set 1
<4>[4294840.246000] audio: streamtype_set: stop rave
<4>[4294840.251000] decode
<4>[4294840.263000] audio: streamtype_set: restart rave
<4>[4294840.268000] set mute 0 (111) 1
<4>[4294840.274000] audio: decoder start 2
<4>[4294840.291000] video delay 0 (0 ms)
<4>[4294840.294000] total video delay: 0 (0 ms)
<4>[4294840.301000] VIDEO0: set streamtype!
<4>[4294840.305000] set H264
<4>[4294840.307000] sw rave disabled!
<4>[4294840.310000] audio delay 18000 (200 ms)
<4>[4294840.314000] total video delay: 18000 (200 ms)
<4>[4294840.322000] start video0 on dmx 0 pid:a3
<4>[4294840.327000] total video delay: 18000 (200 ms)
<4>[4294840.339000] VIDEO0: start decode
<4>[  522.667000] VIDEO0: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[  522.790000] set current avs auto aspect to 16:9
<4>[  522.795000] disable wss on display 0
<4>[  522.799000] set wss 7 on display 1
<4>[  522.803000] set sb to 3(1)
<4>[  560.148000] VIDEO0: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[  560.261000] set current avs auto aspect to 16:9
<4>[  560.266000] disable wss on display 0
<4>[  560.270000] set wss 7 on display 1
<4>[  560.274000] set sb to 3(1)
<4>[ 1020.331000] VIDEO0: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[ 1020.441000] set current avs auto aspect to 16:9
<4>[ 1020.446000] disable wss on display 0
<4>[ 1020.450000] set wss 7 on display 1
<4>[ 1020.453000] set sb to 3(1)
<4>[ 1209.734000] VIDEO0: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[ 1209.862000] set current avs auto aspect to 16:9
<4>[ 1209.866000] disable wss on display 0
<4>[ 1209.870000] set wss 7 on display 1
<4>[ 1209.874000] set sb to 3(1)
<4>[ 1277.496000] VIDEO0: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[ 1277.620000] set current avs auto aspect to 16:9
<4>[ 1277.625000] disable wss on display 0
<4>[ 1277.629000] set wss 7 on display 1
<4>[ 1277.632000] set sb to 3(1)
<4>[ 1305.463000] VIDEO0: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[ 1305.580000] set current avs auto aspect to 16:9
<4>[ 1305.585000] disable wss on display 0
<4>[ 1305.589000] set wss 7 on display 1
<4>[ 1305.592000] set sb to 3(1)
<4>[ 3861.265000] stop pcr0 on dmx 0 pid:a3
<4>[ 3861.270000] stop video0 on dmx 0 pid:a3
<4>[ 3861.277000] VIDEO0: stop decode
<4>[ 3861.280000] VIDEO0: set blank to 1
<4>[ 3861.285000] bcm_audio: got invalid pts (ret 0)!!
<4>[ 3861.290000] audio: decoder stop
<4>[ 3861.306000] stop audio on dmx 0 pid:5c
<4>[ 3861.310000] audio: xpt stop(2)
<4>[ 3861.313000] no decoder left in sync handling so disable xpt_sync
<4>[ 3861.320000] bcm_audio_channel_stop(2) done
<4>[ 3862.413000] VIDEO0: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[ 3862.535000] set current avs auto aspect to 16:9
<4>[ 3862.540000] disable wss on display 0
<4>[ 3862.543000] set wss 7 on display 1
<4>[ 3862.547000] set sb to 3(1)
<6>[ 3874.610000] bcmfb: disable manual blit
<4>[ 3875.521000] VIDEO0: set streamtype!
<4>[ 3875.525000] set MPEG2
<4>[ 3875.527000] sw rave disabled!
<4>[ 3875.530000] VIDEO0: set blank to 0
<4>[ 3875.638000] sync is off so we enable it
<4>[ 3875.642000] playback!
<4>[ 3875.644000] total video delay: 0 (0 ms)
<4>[ 3875.751000] VIDEO0: start decode
<4>[ 3875.766000] flush video decoder
<4>[ 3875.782000] alps_bsbe2 is in powersave mode now
<4>[ 3875.875000] VIDEO0: first pts 0x0
<4>[ 3875.953000] VIDEO0: set blank to 0
<4>[ 3875.959000] VIDEO0: stop decode
<4>[ 3875.963000] VIDEO0: set blank to 0
<4>[ 3875.967000] no decoder left in sync handling so disable xpt_sync
<3>[ 3879.826000] bcm_accel: invalid opcode! 00000080
<6>[ 3879.839000] bcmfb: enable manual blit
<4>[ 3881.050000] alps_bsbe2 is in normal mode now
<4>[ 3881.165000] VIDEO0: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[ 3881.174000] set current avs auto aspect to 16:9
<4>[ 3881.179000] disable wss on display 0
<4>[ 3881.183000] set wss 7 on display 1
<4>[ 3881.187000] set sb to 3(1)
<4>[ 3882.374000] 4013997 ms: 100 
<4>[ 3882.429000] 51 ms: 0 
<4>[ 3883.924000] 1493 ms: 0 
<4>[ 3884.063000] alps_bsbe2 is in powersave mode now
<4>[ 3884.112000] 185 ms: 1 
<4>[ 3884.172000] 57 ms: 2 
<4>[ 3884.534000] 358 ms: 2 
<4>[ 3884.654000] 117 ms: 2 
<4>[ 3885.916000] 1259 ms: 2 
<4>[ 3885.948000] 29 ms: 3 
<4>[ 3885.957000] 6 ms: 3 
<4>[ 3885.963000] 4 ms: 3 
<4>[ 3899.708000] 13742 ms: 3 
<4>[ 3899.717000] 7 ms: 20 
<4>[ 3899.954000] 235 ms: 20 
<4>[ 3900.217000] 259 ms: 20 
<4>[ 3900.224000] 4 ms: 20 
<4>[ 3900.262000] 36 ms: 20 
<4>[ 3900.273000] 8 ms: 21 
<4>[ 3900.281000] 5 ms: 21 
<4>[ 3900.508000] 225 ms: 21 
<4>[ 3901.389000] 878 ms: 21 
<4>[ 3901.427000] 35 ms: 22 
<4>[ 3901.826000] 396 ms: 22 
<4>[ 3901.833000] 5 ms: 22 
<4>[ 3901.869000] 33 ms: 22 
<4>[ 3902.736000] 864 ms: 22 
<4>[ 3902.786000] 47 ms: 23 
<4>[ 3902.837000] 48 ms: 23 
<4>[ 3902.845000] 5 ms: 23 
<4>[ 3902.861000] 14 ms: 23 
<4>[ 3902.959000] 95 ms: 23 
<4>[ 3920.149000] 17187 ms: 23 
<4>[ 3920.159000] 8 ms: 43 
<4>[ 3920.397000] 236 ms: 43 
<4>[ 3920.404000] 4 ms: 43 
<4>[ 3920.530000] 124 ms: 43 
<4>[ 3920.541000] 8 ms: 43 
<4>[ 3920.551000] 7 ms: 43 
<4>[ 3920.569000] 16 ms: 43 
<4>[ 3920.610000] 39 ms: 43 
<4>[ 3920.618000] 5 ms: 43 
<4>[ 3920.659000] 39 ms: 43 
<4>[ 3922.511000] 1850 ms: 43 
<4>[ 3922.963000] 449 ms: 46 
<4>[ 3924.136000] 1170 ms: 46 
<4>[ 3926.428000] 2289 ms: 48 
<4>[ 3926.533000] set current avs auto aspect to 16:9
<4>[ 3926.539000] disable wss on display 0
<4>[ 3926.542000] set wss 7 on display 1
<4>[ 3926.546000] set sb to 3(1)
<4>[ 3926.554000] set current avs auto aspect to 16:9
<4>[ 3926.559000] disable wss on display 0
<4>[ 3926.563000] set wss 7 on display 1
<4>[ 3926.567000] set sb to 3(1)
<4>[ 3926.576000] disable wss on display 0
<4>[ 3926.580000] set wss 7 on display 1
<4>[ 3926.586000] set input to 0
<4>[ 3926.588000] set fb to 2(0)
<4>[ 3926.591000] set current avs auto aspect to 16:9
<4>[ 3926.597000] disable wss on display 0
<4>[ 3926.601000] set wss 7 on display 1
<4>[ 3926.605000] set sb to 3(1)
<4>[ 3926.634000] set ac3 to downmix
<4>[ 3926.638000] audio: streamtype set 1
<4>[ 3926.641000] decode
<4>[ 3926.644000] set mute 0 (111) 0
<4>[ 3926.657000] set aac to downmix
<4>[ 3926.694000] set mute 0 (111) 0
<4>[ 3926.702000] 271 ms: 50 
<4>[ 3926.725000] 19 ms: 50 
<4>[ 3926.745000] 18 ms: 50 
<4>[ 3926.795000] 47 ms: 50 
<4>[ 3930.533000] 3735 ms: 51 
<4>[ 3930.553000] 17 ms: 54 
<4>[ 3931.599000] 1042 ms: 55 
<4>[ 3931.688000] 86 ms: 56 
<4>[ 3932.093000] 402 ms: 56 
<4>[ 3932.126000] 30 ms: 56 
<4>[ 3932.134000] 6 ms: 56 
<4>[ 3932.141000] 4 ms: 56 
<4>[ 3932.175000] 32 ms: 56 
<4>[ 3932.187000] 9 ms: 56 
<4>[ 3932.237000] 47 ms: 56 
<4>[ 3932.431000] 191 ms: 56 
<4>[ 3952.805000] 20371 ms: 56 
<4>[ 3953.022000] 214 ms: 81 
<4>[ 3953.249000] 225 ms: 81 
<4>[ 3953.337000] 85 ms: 81 
<4>[ 3953.402000] 62 ms: 81 
<4>[ 3953.570000] 165 ms: 81 
<4>[ 3953.739000] 167 ms: 81 
<4>[ 3953.788000] 47 ms: 81 
<4>[ 3953.818000] 28 ms: 81 
<4>[ 3953.875000] 54 ms: 81 
<4>[ 3953.987000] 109 ms: 82 
<4>[ 3954.063000] 73 ms: 82 
<4>[ 3954.293000] 227 ms: 82 
<4>[ 3954.738000] 441 ms: 82 
<4>[ 3954.820000] 79 ms: 82 
<4>[ 3954.868000] 46 ms: 82 
<4>[ 3955.279000] 408 ms: 82 
<4>[ 3955.302000] 20 ms: 83 
<4>[ 3955.548000] 244 ms: 83 
<4>[ 3955.570000] 20 ms: 83 
<4>[ 3955.785000] set current avs auto aspect to 16:9
<4>[ 3955.790000] disable wss on display 0
<4>[ 3955.794000] set wss 7 on display 1
<4>[ 3955.798000] set sb to 3(1)
<4>[ 3955.807000] set current avs auto aspect to 16:9
<4>[ 3955.812000] disable wss on display 0
<4>[ 3955.817000] set wss 7 on display 1
<4>[ 3955.821000] set sb to 3(1)
<4>[ 3955.827000] disable wss on display 0
<4>[ 3955.831000] set wss 7 on display 1
<4>[ 3955.838000] set current avs auto aspect to 16:9
<4>[ 3955.843000] disable wss on display 0
<4>[ 3955.847000] set wss 7 on display 1
<4>[ 3955.850000] set sb to 3(1)
<4>[ 3955.883000] set current avs auto aspect to 16:9
<4>[ 3955.888000] disable wss on display 0
<4>[ 3955.891000] set wss 7 on display 1
<4>[ 3955.896000] set sb to 3(1)
<4>[ 3955.902000] set current avs auto aspect to 16:9
<4>[ 3955.907000] disable wss on display 0
<4>[ 3955.911000] set wss 7 on display 1
<4>[ 3955.915000] set sb to 3(1)
<4>[ 3955.924000] disable wss on display 0
<4>[ 3955.927000] set wss 7 on display 1
<4>[ 3955.936000] set current avs auto aspect to 16:9
<4>[ 3955.941000] disable wss on display 0
<4>[ 3955.944000] set wss 7 on display 1
<4>[ 3955.948000] set sb to 3(1)
<4>[ 3955.981000] set current avs auto aspect to 16:9
<4>[ 3955.985000] disable wss on display 0
<4>[ 3955.989000] set wss 7 on display 1
<4>[ 3955.993000] set sb to 3(1)
<4>[ 3956.001000] set current avs auto aspect to 16:9
<4>[ 3956.005000] disable wss on display 0
<4>[ 3956.009000] set wss 7 on display 1
<4>[ 3956.013000] set sb to 3(1)
<4>[ 3956.020000] disable wss on display 0
<4>[ 3956.024000] set wss 7 on display 1
<4>[ 3956.033000] set current avs auto aspect to 16:9
<4>[ 3956.038000] disable wss on display 0
<4>[ 3956.042000] set wss 7 on display 1
<4>[ 3956.046000] set sb to 3(1)
<4>[ 3956.078000] set current avs auto aspect to 16:9
<4>[ 3956.083000] disable wss on display 0
<4>[ 3956.087000] set wss 7 on display 1
<4>[ 3956.090000] set sb to 3(1)
<4>[ 3956.098000] set current avs auto aspect to 16:9
<4>[ 3956.102000] disable wss on display 0
<4>[ 3956.106000] set wss 7 on display 1
<4>[ 3956.110000] set sb to 3(1)
<4>[ 3956.117000] disable wss on display 0
<4>[ 3956.120000] set wss 7 on display 1
<4>[ 3956.127000] set current avs auto aspect to 16:9
<4>[ 3956.132000] disable wss on display 0
<4>[ 3956.136000] set wss 7 on display 1
<4>[ 3956.140000] set sb to 3(1)
<4>[ 3956.173000] set current avs auto aspect to 16:9
<4>[ 3956.179000] disable wss on display 0
<4>[ 3956.183000] set wss 7 on display 1
<4>[ 3956.187000] set sb to 3(1)
<4>[ 3956.193000] set current avs auto aspect to 16:9
<4>[ 3956.199000] disable wss on display 0
<4>[ 3956.202000] set wss 7 on display 1
<4>[ 3956.206000] set sb to 3(1)
<4>[ 3956.240000] set current avs auto aspect to 16:9
<4>[ 3956.245000] disable wss on display 0
<4>[ 3956.248000] set wss 7 on display 1
<4>[ 3956.252000] set sb to 3(1)
<4>[ 3956.262000] set current avs auto aspect to 16:9
<4>[ 3956.266000] disable wss on display 0
<4>[ 3956.270000] set wss 7 on display 1
<4>[ 3956.274000] set sb to 3(1)
<4>[ 3956.281000] disable wss on display 0
<4>[ 3956.285000] set wss 7 on display 1
<4>[ 3956.292000] set current avs auto aspect to 16:9
<4>[ 3956.297000] disable wss on display 0
<4>[ 3956.301000] set wss 7 on display 1
<4>[ 3956.305000] set sb to 3(1)
<4>[ 3956.324000] 752 ms: 83 
<4>[ 3956.337000] 11 ms: 84 
<4>[ 3956.521000] 182 ms: 84 
<4>[ 3959.148000] 2625 ms: 84 
<4>[ 3959.384000] 234 ms: 87 
<4>[ 3959.675000] 288 ms: 87 
<4>[ 3965.451000] 5773 ms: 88 
<4>[ 3966.800000] 1347 ms: 91 
<4>[ 3972.972000] 6169 ms: 92 
<4>[ 3973.158000] 182 ms: 99 
<4>[ 3973.191000] 31 ms: 99 
<4>[ 3973.199000] 5 ms: 99 
<4>[ 3976.650000] alps_bsbe2 is in normal mode now
<4>[ 3979.792000] pilot_off!
<4>[ 3979.923000] start pcr0 on dmx 0 pid:a3 index 1
<4>[ 3979.930000] start audio on dmx 0 pid:5c
<4>[ 3979.934000] audio xpt start
<4>[ 3979.937000] sync is off so we enable it
<4>[ 3979.942000] demux-index 0 pcr0pid a3
<4>[ 3979.945000] using 1 as pcr0 pidchannel
<4>[ 3979.951000] AC3
<4>[ 3979.954000] audio: decoder start 2
<4>[ 3979.971000] video delay 0 (0 ms)
<4>[ 3979.974000] total video delay: 0 (0 ms)
<4>[ 3979.981000] VIDEO0: set streamtype!
<4>[ 3979.985000] set H264
<4>[ 3979.987000] sw rave disabled!
<4>[ 3979.990000] audio delay 18000 (200 ms)
<4>[ 3979.994000] total video delay: 18000 (200 ms)
<4>[ 3980.002000] start video0 on dmx 0 pid:a3
<4>[ 3980.006000] total video delay: 18000 (200 ms)
<4>[ 3980.018000] VIDEO0: start decode
<4>[ 3989.910000] stop pcr0 on dmx 0 pid:a3
<4>[ 3989.916000] stop video0 on dmx 0 pid:a3
<4>[ 3989.922000] VIDEO0: stop decode
<4>[ 3989.926000] VIDEO0: set blank to 1
<4>[ 3989.931000] audio: decoder stop
<4>[ 3989.947000] stop audio on dmx 0 pid:5c
<4>[ 3989.951000] audio: xpt stop(2)
<4>[ 3989.954000] no decoder left in sync handling so disable xpt_sync
<4>[ 3989.961000] bcm_audio_channel_stop(2) done

**Comment by fairbird** [comment]
Old devices doesn't support H264 then can not run streaming as H264
<4>[4294840.305000] set H264
But wait @Hains to more confirm
