### ISSUE TITLE
k1 plus error

### ISSUE THREAD

**Issue by ardasa** [OpenVisionE2/openvision-oe#20]
I have already collected an image 3 times.and every time this error.

| Makefile:399: recipe for target 'all-recursive' failed
| make: *** [all-recursive] Error 1
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /home/aa/Desktop/k2plus/openpli-oe-core/build/tmp/work/k1plus-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+7ffc2cee48-r0/temp/log.do_compile.22423)
ERROR: Task (/home/aa/Desktop/k2plus/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2-plugin-systemplugins-servicemp3.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5209 tasks of which 5107 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/aa/Desktop/k2plus/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2-plugin-systemplugins-servicemp3.bb:do_compile
Summary: There were 2 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
Makefile:125: recipe for target 'image' failed
make: *** [image] Error 1
-e 
-e Done, the compiled image is in build/tmp/deploy/images/k1plus folder!
-e It's a zipped file like openvision-enigma2-develop-k1plus.zip
aa@aa-N81Vp:~/Desktop/k2plus/openpli-oe-core/openvision-oe$

**Comment by persianpros** [comment]
You need to use "update.sh" then compile again.

**Comment by Hains** [comment]
Just try to delete the tmp directory first.
```
rm -r build/tmp
```
It keeps the buildstats (sstate-cache), so you don't need to compile everything again.

**Comment by ardasa** [comment]
thank.I will try.

**Comment by ardasa** [comment]
Did not work out.error.Can someone collect for k1plus?

| Makefile:399: recipe for target 'all-recursive' failed
| make: *** [all-recursive] Error 1
| ERROR: Function failed: do_compile (log file is located at /home/aa/Desktop/k2plus/openpli-oe-core/build/tmp/work/k1plus-oe-linux/enigma2-plugin-systemplugins-servicemp3/gitAUTOINC+7ffc2cee48-r0/temp/log.do_compile.10566)
ERROR: Task (/home/aa/Desktop/k2plus/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2-plugin-systemplugins-servicemp3.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5144 tasks of which 4115 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/aa/Desktop/k2plus/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2-plugin-systemplugins-servicemp3.bb:do_compile
Summary: There were 17 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
Makefile:125: recipe for target 'image' failed
make: *** [image] Error 1
-e 
-e Done, the compiled image is in build/tmp/deploy/images/ folder!
-e It's a zipped file like openvision-enigma2-develop-.zip
aa@aa-N81Vp:~/Desktop/k2plus/openpli-oe-core/openvision-oe$

**Comment by Hains** [comment]
The k1plus builds without any problem. 
Apparently your openvision-oe is for some reason not up to date.
Delete openvision-oe, clone again and run update.sh.
I don't expect an entire rebuild of all packages.

Well, i have test image for you.
http://www.mediafire.com/file/xr3lkh6xtot9n3v/openvision-enigma2-develop-7.0-r1-k1plus_sdcard.zip/file

According to an user, the image doesn't work. GSOD.
Try it and perhaps you're lucky.

**Comment by ardasa** [comment]
thank.

**Comment by Hains** [comment]
Regarding crash, continue discussion here:
https://github.com/OpenVisionE2/openvision-oe/issues/21
