### ISSUE TITLE
wetekplay2 fails to compile

### ISSUE THREAD

**Issue by Ntemis** [OpenVisionE2/openvision-oe#21]
NOTE: openssl-native exists in sysroot, skipping
| NOTE: sqlite3-native exists in sysroot, skipping
| NOTE: xz-native exists in sysroot, skipping
| NOTE: pkgconfig-native exists in sysroot, skipping
| NOTE: expat-native exists in sysroot, skipping
| NOTE: readline-native exists in sysroot, skipping
| NOTE: opkg-utils exists in sysroot, skipping
| NOTE: linux-libc-headers exists in sysroot, skipping
| NOTE: gettext exists in sysroot, skipping
| NOTE: cryptodev-linux exists in sysroot, skipping
| NOTE: libgcc exists in sysroot, skipping
| NOTE: ncurses exists in sysroot, skipping
| NOTE: m4-native exists in sysroot, skipping
| NOTE: upx-native exists in sysroot, skipping
| NOTE: pigz-native exists in sysroot, skipping
| NOTE: ncurses-native exists in sysroot, skipping
| NOTE: expat exists in sysroot, skipping
| NOTE: ucl-native exists in sysroot, skipping
| DEBUG: Python function extend_recipe_sysroot finished
| DEBUG: Executing shell function do_install
| ERROR: python setup.py install execution failed.
| running install
| error: invalid Python installation: unable to open /home/demetris/openpli-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-e2iplayer/gitAUTOINC+0bf0efaf05-r0/recipe-sysroot/usr/lib/python2.7/config/Makefile (No such file or directory)
| ERROR: Function failed: do_install (log file is located at /home/demetris/openpli-oe-core/build/tmp/work/all-oe-linux/enigma2-plugin-extensions-e2iplayer/gitAUTOINC+0bf0efaf05-r0/temp/log.do_install.20291)
ERROR: Task (/home/demetris/openpli-oe-core/openvision-oe/recipes-openvision/enigma2-plugins/enigma2-plugin-extensions-e2iplayer.bb:do_install) failed with exit code '1'
NOTE: Tasks Summary: Attempted 7769 tasks of which 9 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/demetris/openpli-oe-core/openvision-oe/recipes-openvision/enigma2-plugins/enigma2-plugin-extensions-e2iplayer.bb:do_install
Summary: There were 30 WARNING messages shown.
Summary: There were 17 ERROR messages shown, returning a non-zero exit code.
Makefile:65: recipe for target 'image' failed
make: *** [image] Error 1
-e 
-e Done, the compiled image is in build/tmp/deploy/images/wetekplay2 folder!
-e It's a zipped file like openvision-enigma2-develop-multilanguage-7.3-r73-wetekplay2.zip

**Comment by persianpros** [comment]
Try again now.

**Comment by Ntemis** [comment]
Everything is in order now, thanks
