### ISSUE TITLE
crash of K1 plus

### ISSUE THREAD

**Issue by blueveryday** [OpenVisionE2/openvision-oe#21]
Sir , thank you so much firstly. 
I compile the k1plus(S905 CPU,not S905D, 8g flash and 1g RAM) image by myself. 
and flash it into TF card . booting , 
I get a green screen on TV. 
this attachment is enigma2_crash.log file. hope to help you check these errors. 
Thank you very much . 
I had send a email to crash@openvision.tech including enigma2_crash.log file.
best regards.

**Comment by ardasa** [comment]
You can share the image k1plus S905?thank.

**Comment by blueveryday** [comment]
> You can share the image k1plus S905?thank.

Image of k1plus couldn't boot this box .

**Comment by ardasa** [comment]
yes. dark screen.
