### ISSUE TITLE
Building image for raspberrypi3

### ISSUE THREAD

**Issue by robo65536** [OpenVisionE2/openvision-oe#22]
Building image for raspberrypi3
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
Parsing recipes: 100% |##########################################| Time: 0:01:52
Parsing of 2873 .bb files complete (0 cached, 2873 parsed). 3731 targets, 472 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.34.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "ubuntu-18.04"
TARGET_SYS        = "arm-oe-linux-gnueabi"
MACHINE           = "raspberrypi3"
DISTRO            = "openvision"
DISTRO_VERSION    = "develop"
TUNE_FEATURES     = "arm armv7ve vfp thumb neon vfpv4 callconvention-hard cortexa7"
TARGET_FPU        = "hard"
meta-oe           
meta-filesystems  
meta-multimedia   
meta-networking   
meta-python       
meta-webserver    = "HEAD:dfbdd28d206a74bf264c2f7ee0f7b3e5af587796"
meta              = "HEAD:93dd2f9f3edf0584f9e806c629611d645dd72dbf"
meta-openpli      = "develop:424b79a7b0a335546462e24d5fe4ba8639923efc"
meta-qt5          = "HEAD:c6aa602d0640040b470ee81de39726276ddc0ea3"
meta-cube         = "HEAD:ad3c13055972bec75b08305eebd81947e6af300d"
meta-dm800        = "HEAD:5b687de795bb3c234acdb6b67acb82ca74d96e45"
meta-hypercube    = "HEAD:a40ff8fced3e9471978ed0648099d44114cc6202"
meta-linkdroid    = "HEAD:87004e9fb6372a1718dab210851ae85459ea9322"
meta-minix        = "HEAD:d34a54545d3be5024345aa69476857768f8e0554"
meta-odroid       = "HEAD:2a71085ec1ac38b21ddc3c3182c00c306b740f9c"
meta-raspberrypi  = "HEAD:4843a5ce6a03c6544ead19cea8c2aa705c09e212"
meta-wetek        = "HEAD:d5dc117bd65c775821c82210e41eb0c57a361251"
openvision-oe     = "develop:eb0c85f9314444bf522f55f90b519ede870498c4"

Initialising tasks: 100% |#######################################| Time: 0:00:12
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: libmpc-native-1.0.3-r0 do_fetch: Failed to fetch URL http://www.multiprecision.org/mpc/download/mpc-1.0.3.tar.gz, attempting MIRRORS if available
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt220 pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt220. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt200 pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt200. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt100 pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt100. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt52 pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt52. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt102 pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt102. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/d/dumb pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/d/dumb. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/x/xterm-xfree86 pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/x/xterm-xfree86. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/x/xterm-256color pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/x/xterm-256color. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/x/xterm-color pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/x/xterm-color. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/l/linux pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/l/linux. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/r/rxvt pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/r/rxvt. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/a/ansi pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/a/ansi. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/s/screen-256color pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/s/screen-256color. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/s/screen pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/s/screen. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/s/sun pointing at /home/user/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/s/sun. Please replace this with a relative link.
WARNING: bzip2-native-1.0.6-r5 do_fetch: Checksum mismatch for local file /home/user/openpli-oe-core/sources/bzip2-1.0.6.tar.gz
Cleaning and trying again.
WARNING: bzip2-native-1.0.6-r5 do_fetch: Renaming /home/user/openpli-oe-core/sources/bzip2-1.0.6.tar.gz to /home/user/openpli-oe-core/sources/bzip2-1.0.6.tar.gz_bad-checksum_1512da05e140a47018f6997a697c6cff
WARNING: bzip2-native-1.0.6-r5 do_fetch: Checksum failure encountered with download of http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz - will attempt other sources if available
WARNING: popt-native-1.16-r3 do_fetch: Failed to fetch URL http://rpm5.org/files/popt/popt-1.16.tar.gz, attempting MIRRORS if available
WARNING: libpcre-native-8.40-r0 do_fetch: Failed to fetch URL ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.40.tar.bz2, attempting MIRRORS if available
WARNING: libpng-native-1.6.28-r0 do_fetch: Failed to fetch URL http://distfiles.gentoo.org/distfiles/libpng-1.6.28.tar.xz, attempting MIRRORS if available
ERROR: linux-raspberrypi-1_4.19.95+git0d72d83ec92acda1e8cbad0d4213a5ec2b3f2e1b-openvision do_kernel_checkout: Function failed: do_kernel_checkout (log file is located at /home/user/openpli-oe-core/build/tmp/work/raspberrypi3-oe-linux-gnueabi/linux-raspberrypi/1_4.19.95+git0d72d83ec92acda1e8cbad0d4213a5ec2b3f2e1b-openvision/temp/log.do_kernel_checkout.36555)
ERROR: Logfile of failure stored in: /home/user/openpli-oe-core/build/tmp/work/raspberrypi3-oe-linux-gnueabi/linux-raspberrypi/1_4.19.95+git0d72d83ec92acda1e8cbad0d4213a5ec2b3f2e1b-openvision/temp/log.do_kernel_checkout.36555
Log data follows:
| DEBUG: Executing shell function do_kernel_checkout
| Initialized empty Git repository in /home/user/openpli-oe-core/build/tmp/work-shared/raspberrypi3/kernel-source/.git/
| 
| *** Please tell me who you are.
| 
| Run
| 
|   git config --global user.email "you@example.com"
|   git config --global user.name "Your Name"
| 
| to set your account's default identity.
| Omit --global to set the identity only in this repository.
| 
| fatal: unable to auto-detect email address (got 'user@ubnt-vmpc.(none)')
| error: pathspec 'master' did not match any file(s) known to git.
| ERROR: Function failed: do_kernel_checkout (log file is located at /home/user/openpli-oe-core/build/tmp/work/raspberrypi3-oe-linux-gnueabi/linux-raspberrypi/1_4.19.95+git0d72d83ec92acda1e8cbad0d4213a5ec2b3f2e1b-openvision/temp/log.do_kernel_checkout.36555)
ERROR: Task (/home/user/openpli-oe-core/openvision-oe/meta-raspberrypi/recipes-bsp/linux/linux-raspberrypi_4.19.bb:do_kernel_checkout) failed with exit code '1'
NOTE: Tasks Summary: Attempted 904 tasks of which 0 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/user/openpli-oe-core/openvision-oe/meta-raspberrypi/recipes-bsp/linux/linux-raspberrypi_4.19.bb:do_kernel_checkout
Summary: There were 7 WARNING messages shown.
Summary: There were 16 ERROR messages shown, returning a non-zero exit code.
Makefile:65: recipe for target 'image' failed
make: *** [image] Error 1

Done, the compiled image is in build/tmp/deploy/images/raspberrypi3 folder!
It's a zipped file like openvision-enigma2-develop-multilanguage-7.3-r73-raspberrypi3.zip

**Comment by persianpros** [comment]
For me there's no problem and I did test it myself.

**Comment by robo65536** [comment]
What main problem in my situation? Missing fetch files or another?

**Comment by persianpros** [comment]
No idea, I'm fine with the build so OV is ok.

**Comment by petrkr** [comment]
Same problem here. Seems you have already debugged environment, so that is why for you and only you it working. But it does not work to anyone else. Would be helpful if you can share solution. Thanks
