### ISSUE TITLE
Some bootlogo

### ISSUE THREAD

**Issue by ycf83** [OpenVisionE2/openvision-oe#23]
hi,  i try to make bootlogo for openvision ;

![wallhaven-6416v](https://user-images.githubusercontent.com/39797567/50698428-3638f100-1045-11e9-8a2b-b714d64707af.jpg)

![wallhaven-52603v](https://user-images.githubusercontent.com/39797567/50698600-a3e51d00-1045-11e9-94b4-2fa960e114b8.png)

![tet25](https://user-images.githubusercontent.com/39797567/50698895-90868180-1046-11e9-92c5-5cdc2b547d15.png)

![wallhaven-146575v](https://user-images.githubusercontent.com/39797567/50700535-10164f80-104b-11e9-83b9-fefd4a0389b7.jpg)

**Comment by ycf83** [comment]
ok, thnk's , check this  : 

![wallhaven-146575](https://user-images.githubusercontent.com/39797567/50705035-b9644200-1059-11e9-86b4-9430a5d15376.jpg)

**Comment by persianpros** [comment]
Yeah that's what I'm talking about, @Hains if you like this too please add it as the default bootlogo :)

**Comment by persianpros** [comment]
This is better but we need the slogan too, for example smaller under Open Vision :+1:

**Comment by Hains** [comment]
Does all our boxes support Full HD OSD layer.
Otherwise the resolution must be 1280x720.

**Comment by Hains** [comment]
Hmm. so the 1280x720 resolution is obsolete for all HD boxes.
I see indeed writing  to /dev/dvb/adapter0/video0.
I recall something with iframe..
But let's go for Full HD.

**Comment by ycf83** [comment]
ok, i hope u like it

![wallhav](https://user-images.githubusercontent.com/39797567/50710350-0ef51a80-106b-11e9-8f9a-46b19720c225.jpg)

**Comment by Hains** [comment]
OK :+1:  
Everyone agree?
If so, i push bootlogo.mvi to openvision-oe.

**Comment by jerrybutler1** [comment]
good evening to all Yes, it is beautiful.

**Comment by Hains** [comment]
Pushed.

**Comment by HFX1958** [comment]
A bootlogo whit a beautiful woman  that is what very nice is

**Comment by persianpros** [comment]
LOL I vote no for pictures with humans ;)

**Comment by jerrybutler1** [comment]
hello I'm against it too.
