### ISSUE TITLE
Image for kii pro (I can't do it 😥)

### ISSUE THREAD

**Issue by gridi88** [OpenVisionE2/openvision-oe#25]
Hello everyone.  I am wasting many evenings trying and trying to compile an image for my old kii pro box, but I am not succeeding in any way.  I kindly ask the developers to make one for me or those who have already compile it, to post the link to download it. thank you in advance.

**Comment by persianpros** [comment]
Hello,

You could donate via https://forum.openvision.tech/app.php/donate then let me know I will compile an image for you.

Regards,
Persian Prince

**Comment by gridi88** [comment]
> Hello,
> 
> You could donate via https://forum.openvision.tech/app.php/donate then let me know I will compile an image for you.
> 
> Regards,
> Persian Prince

I can gladly donate, I am a big fan of Enigma2, and I have always donated to those who put their commitment on a project. therefore, I do it right here for you too. my Telegram contact t.me/gridi88 or you can find me in Enigma2 group t.me/Enigma2_Spain . Cheers
