### ISSUE TITLE
Create image for UFS 910 (Fulan)

### ISSUE THREAD

**Issue by Schaagi** [OpenVisionE2/openvision-oe#26]
I have compiled the image with the newest Linux Mint edition (19.1). There are some errors, but the image has been built.
_**ERROR: When reparsing /home/hansjoerg/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, 
the basehash value changed from 364633facf253f6d2c4bf99e23c8564f to a9ab80bd7471b0e545b59da4377a7938. The metadata is not deterministic and this needs to be fixed.**_
I have uploaded the "openvision-enigma2-develop-7.0-r2-ufs910.rootfs.tar.gz" to the receiver, because the xxx.zip file is only for FLASH. Because the memory is to small, I need to install it to an USB stick (mini-uboot)
After first boot up, nothing happens. After waiting for a while and restart again, I can see the bootlogo of the openvision image, then waiting and waiting, but this is the end.
Any ideas ?
Best regards
Schaagi

**Comment by Hains** [comment]
Be sure you have the latest enigma2.
There was a problem which causes an endless loop for all boxes.
I updated enigma2-enigma2-sh4 repo a few hours ago with fix.

**Comment by Hains** [comment]
BTW te error:
```
ERROR: When reparsing /home/hansjoerg/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install,
the basehash value changed from 364633facf253f6d2c4bf99e23c8564f to a9ab80bd7471b0e545b59da4377a7938. The metadata is not deterministic and this needs to be fixed.
```
is harmless. 
You can ignore it, although we still need to fix it.

**Comment by persianpros** [comment]
We don't know how to pack other sh4 boxes  so you're on your own.
