### ISSUE TITLE
installed on sh4 successfully,thanks to all the team

### ISSUE THREAD

**Issue by ahmedmoselhi** [OpenVisionE2/openvision-oe#29]
i have successufully compiled and installed image on my sh4 spark st7111 stb here is the images
![screenshot_2019-01-08_17-10-32](https://user-images.githubusercontent.com/13953258/50840311-dc993500-136a-11e9-9593-eafe896ef5e3.jpg)
![screenshot_2019-01-08_17-10-00](https://user-images.githubusercontent.com/13953258/50840312-dc993500-136a-11e9-9c94-fa1297360526.jpg)
![screenshot_2019-01-08_17-10-13](https://user-images.githubusercontent.com/13953258/50840313-dd31cb80-136a-11e9-8866-2d8915dc26b5.jpg)
thanks for @persianpros and all other contributers and i want to ask some view questions:
1- will this build support blindscan feature on our st7111 tuners (stv090x) as it's along waited feature??
2- will this build support direct tuning and scanning of t2-mi channels on 4.8e , 53e , ... etc???
3- on xmodem , what types of usb modems supported ???

**Comment by ahmedmoselhi** [comment]
@jerrybutler1 first, you need a good internet connection
second, you may need to try the build process after every error message and even delete the build folder if the error persist and start build from scratch
third,the build takes considerably very long time and needs a computer with good CPU 
fourth, it's preferable to build under ubuntu 16.04 or ubuntu 18.04

**Comment by jerrybutler1** [comment]
@ahmedmoselhi  I compiled for octagon sf8008 but there's no notice of the plugins.

**Comment by ahmedmoselhi** [comment]
@jerrybutler1 first you need rs232 cable connected to both receiver and computer 
then run a telnet client ( like putty) with speed 115200
3- write down the output here

**Comment by kueken** [comment]
a little bit of crossover here, do not you think?
To the questions above ...
We patched everything, just try it and give feedback.
Unfortunately, I can no longer check the 7111, which is broken.

**Comment by ahmedmoselhi** [comment]
@kueken would you please give me link to blindscan plugin?
