### ISSUE TITLE
PluginSkinMover

### ISSUE THREAD

**Issue by persianpros** [OpenVisionE2/openvision-oe#31]
Hi my friends,

Anybody knows where could I find the latest version of "PluginSkinMover" plugin?

I want to add it for smallflash STBs and maintain that plugin on our github.

**Comment by BarviX6** [comment]
[enigma2-plugin-extensions-pluginskinmover_0.6_all.zip](https://github.com/OpenVisionE2/openvision-oe/files/2740735/enigma2-plugin-extensions-pluginskinmover_0.6_all.zip)

**Comment by persianpros** [comment]
Thanks a lot 👍
