### ISSUE TITLE
UFS910 (Fulan) - Boot stop

### ISSUE THREAD

**Issue by Schaagi** [OpenVisionE2/openvision-oe#33]
I compiled today's image for UFS910.
To check the problem with booting, I logged the boot process with Hyperterminal.
The first start after installing the image ends with the following message.

Waiting 6sec before mounting root device...
scsi 2:0:0:0: Direct-Access     JetFlash Transcend 16GB   8.07 PQ: 0 ANSI: 4
sd 2:0:0:0: [sdb] 31358976 512-byte logical blocks: (16.0 GB/14.9 GiB)
sd 2:0:0:0: [sdb] Write Protect is off
sd 2:0:0:0: [sdb] Assuming drive cache: write through
sd 2:0:0:0: [sdb] Assuming drive cache: write through
 sdb: sdb1
sd 2:0:0:0: [sdb] Assuming drive cache: write through
sd 2:0:0:0: [sdb] Attached SCSI removable disk
ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
EXT2-fs warning: mounting unchecked fs, running e2fsck is recommended
VFS: Mounted root (ext2 filesystem) on device 8:3.
Freeing unused kernel memory: 116k freed
Warning: unable to open an initial console.
EXT4-fs (sda2): warning: mounting unchecked fs, running e2fsck is recommended
EXT4-fs (sda2): mounted filesystem without journal
EXT4-fs (sda4): warning: mounting unchecked fs, running e2fsck is recommended
EXT4-fs (sda4): mounted filesystem without journal
EXT4-fs (sdb1): warning: maximal mount count reached, running e2fsck is recommen
ded
EXT4-fs (sdb1): mounted filesystem with ordered data mode
**Kathrein UFS910 VFD module initializing**

After 20 minutes I rebooted the image and got the following message:

input: Kathrein UFS-910 frontpanel buttons as /devices/virtual/input/input1
Registered led device: ufs910:green
Registered led device: ufs910:orange
Registered led device: ufs910:red
zram: Creating 1 devices ...
ALSA: Restoring mixer settings...
No state is present for card STx7100
Found hardware: "STx7100" "" "" "" ""
Hardware is initialized using a generic method
No state is present for card STx7100
No state is present for card MIXER0
Found hardware: "Pseudo Mixer" "Pseudo Mixer" "" "" ""
Hardware is initialized using a generic method
vm.dirty_writeback_centisecs = 300
vm.dirty_background_ratio = 1
No state is present for card MIXER0
vm.dirty_ratio = 60
INIT: Entering runlevel: 3
Configuring network interfaces... ip: RTNETLINK answers: File exists
udhcpc: option -h NAME is deprecated, use -x hostname:NAME
udhcpc (v1.24.1) started
Sending discoverDisabling IRQ #2
...
**Sending discover...**

I have tried to restart several times, the log is identical. This is only an excerpt from the log. If you need the complete log, I can upload it.

Best regards
Schaagi

**Comment by persianpros** [comment]
As we changed so many things you need to compile and test again.
