### ISSUE TITLE
Failed to fetching submodules from git.

### ISSUE THREAD

**Issue by Shadowman94** [OpenVisionE2/openvision-oe#36]
Hi, i tried to compile vision image for spark, but cant download modules source from git.

error: Server does not allow request for unadvertised object 9deba9383e7d0684f61bad0b8d508a33cc29209f
Fetched in submodule path 'meta-dinobot', but it did not contain 9deba9383e7d0684f61bad0b8d508a33cc29209f. Direct fetching of that commit failed.

**Comment by persianpros** [comment]
We don't have this problem so no idea, sorry.

**Comment by Shadowman94** [comment]
I think the problem is meta-dinobot  linket as submodule to this repo, but its not updated after the last commit in meta-dinobot
