### ISSUE TITLE
Help to compile for rare SH4 boxes

### ISSUE THREAD

**Issue by persianpros** [OpenVisionE2/openvision-oe#39]
I just added the needed sources for "cuberevo_9500hd"

but I couldn't compile successfully and I need help to fix the errors ...

**Comment by sid8796** [comment]
vip1_v2
vip2_v1
https://bitbucket.org/sid8796/vip/src/master/
I can help, but a little later. Ok?

**Comment by sid8796** [comment]
These are clones hl 101, the manufacturer of fulan. I will explain later.

**Comment by persianpros** [comment]
I can't access bitbucket in my country so I just imported it here: https://github.com/persianpros/vip

**Comment by backup1977** [comment]
Hi, all cuberevo only need usb image with tar.gz for flashing, and does not need root.img and uImage

ghani

**Comment by persianpros** [comment]
Yeah vip1_v2 is ok thanks to you 👍 

I'm compiling for vip2_v1 now

**Comment by sid8796** [comment]
updated drivers vip2_v1

**Comment by Hains** [comment]
For cuberevo_9500hd, i think it must use linux-libc-headers 2.6.32 instead of 3.4.100.
I'm testing now.

**Comment by persianpros** [comment]
I just fixed the kernel for cuberevo_9500hd but fulan-dvb-modules is not ok ...

**Comment by persianpros** [comment]
vip2_v1 is ok now, thanks to @sid8796  👍

**Comment by persianpros** [comment]
cuberevo_9500hd is ok now thanks to me LOL

Thank you all 👍
