### ISSUE TITLE
error building sh4

### ISSUE THREAD

**Issue by ahmedmoselhi** [OpenVisionE2/openvision-oe#4]
ERROR: rtl8723bs-4.4.1-r0 do_patch: Command Error: 'quilt --quiltrc /home/ahmed/openpli-oe-core/build/tmp/work/spark-oe-linux/rtl8723bs/4.4.1-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Patch rt8723bs_sh4.patch is already applied; check your series file
ERROR: rtl8723bs-4.4.1-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/ahmed/openpli-oe-core/build/tmp/work/spark-oe-linux/rtl8723bs/4.4.1-r0/temp/log.do_patch.10800
ERROR: Task (/home/ahmed/openpli-oe-core/openvision-oe/recipes-connectivity/realtek/rtl8723bs_4.4.1.bb:do_patch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5270 tasks of which 5248 didn

**Comment by persianpros** [comment]
It should be ok now.
