### ISSUE TITLE
Building k3pro image.

### ISSUE THREAD

**Issue by semenby** [OpenVisionE2/openvision-oe#4]
Hi,
When I am building k3pro image I receive the next errors: 
WARNING: firmware-ap6xxx-mecool-1.0-r0 do_populate_lic: Could not copy license file /opt/projects/openpli-oe-core/build/tmp/work/all-oe-linux/firmware-ap6xxx-mecool/1.0-r0/LICENSE-CLOSE to /opt/projects/openpli-oe-core/build/tmp/work/all-oe-linux/firmware-ap6xxx-mecool/1.0-r0/license-destdir/firmware-ap6xxx-mecool/LICENSE-CLOSE: [Errno 2] No such file or directory: '/opt/projects/openpli-oe-core/build/tmp/work/all-oe-linux/firmware-ap6xxx-mecool/1.0-r0/LICENSE-CLOSE'
ERROR: firmware-ap6xxx-mecool-1.0-r0 do_populate_lic: QA Issue: firmware-ap6xxx-mecool: LIC_FILES_CHKSUM points to an invalid file: /opt/projects/openpli-oe-core/build/tmp/work/all-oe-linux/firmware-ap6xxx-mecool/1.0-r0/LICENSE-CLOSE [license-checksum]

ERROR: openvision-version-info-7.0-r7 do_install: Taskhash mismatch 282ea6befc7f11d3fe7a29681574599b versus 603e6b63218a83ac80acc458fe44ef78 for /opt/projects/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install

ERROR: Taskhash mismatch 282ea6befc7f11d3fe7a29681574599b versus 603e6b63218a83ac80acc458fe44ef78 for /opt/projects/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-veron-version-info.bb.do_install

Can you fix it?
Thank you very much.

**Comment by persianpros** [comment]
You can ignore these kind of errors and warnings as they won't effect the compiled image.

Just for your information: https://github.com/OpenVisionE2/openvision-oe#support :

- Do we provide support for self-building? No! We prefer to work on our projects.
