### ISSUE TITLE
Can't build for optimussos2plus

### ISSUE THREAD

**Issue by TodorGeshev** [OpenVisionE2/openvision-oe#4]
Here is log file
make[1]: Leaving directory '/other/src/vision/openpli-oe-core/build/tmp/work/optimussos2plus-oe-linux/mt7603u/1.1.2-r0/git/tools'
/other/src/vision/openpli-oe-core/build/tmp/work/optimussos2plus-oe-linux/mt7603u/1.1.2-r0/git/tools/bin2h
make[1]: Entering directory '/other/src/vision/openpli-oe-core/build/tmp/work-shared/optimussos2plus/kernel-source'
make -f Makefile modules
make[2]: Entering directory '/other/src/vision/openpli-oe-core/build/tmp/work-shared/optimussos2plus/kernel-source'
make[1]: Entering directory '/other/src/vision/openpli-oe-core/build/tmp/work-shared/optimussos2plus/kernel-source'
make -f Makefile vmlinux
make[2]: Entering directory '/other/src/vision/openpli-oe-core/build/tmp/work-shared/optimussos2plus/kernel-source'
chipset = mt7603u
make[3]: *** No rule to make target 'vmlinux'.  Stop.
Makefile:130: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
make[2]: Leaving directory '/other/src/vision/openpli-oe-core/build/tmp/work-shared/optimussos2plus/kernel-source'
makefile:16: recipe for target 'default' failed
make[1]: *** [default] Error 2
make[1]: Leaving directory '/other/src/vision/openpli-oe-core/build/tmp/work-shared/optimussos2plus/kernel-source'
Makefile:291: recipe for target 'plug_in' failed
make: *** [plug_in] Error 2
make: *** Waiting for unfinished jobs....

**Comment by persianpros** [comment]
Don't use "feed", go normal it should be fine.

Seems https://github.com/OpenVisionE2/openvision-oe/blob/develop/recipes-openvision/images/openvision-enigma2-feed.bb#L139 isn't compatible with your STB.

**Comment by TodorGeshev** [comment]
Or maybe add optimuoss2plus to the MACHINE list ?  Is this module for wifi only ?

**Comment by persianpros** [comment]
Yep that's for extra wifi support so don't worry, I have to add more machines to exceptions.

**Comment by TodorGeshev** [comment]
I still have to change openvision-enigma2-feed to build feed...
I have other problem too. Fallback tuner not working. There is established connection to other receiver but no picture. I think a month ago is working
Thanks
