### ISSUE TITLE
Compiling for Dreambox, I get these 16 errors for all models

### ISSUE THREAD

**Issue by Toysoft** [OpenVisionE2/openvision-oe#43]
Compiling for Dreambox, I get these 16 errors for all models

ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: openvision-version-info-7.0-r4 do_install: Taskhash mismatch 3b1213a0f6fda1c5936467d3e2804e03 versus a550ecb076ba53cb4b398f196354227f for /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install
ERROR: Taskhash mismatch 3b1213a0f6fda1c5936467d3e2804e03 versus a550ecb076ba53cb4b398f196354227f for /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/openvision/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 2943a724cca9ab9b66ad5220c56c1b33 to 7fa4d61fa5ea992548f7203f9ae23ca4. The metadata is not deterministic and this needs to be fixed.

Summary: There were 16 WARNING messages shown.
Summary: There were 16 ERROR messages shown, returning a non-zero exit code.
Makefile:125: recipe for target 'image' failed
make: *** [image] Error 1

**Comment by persianpros** [comment]
It's not important just ignore it for now.
