### ISSUE TITLE
hostapd

### ISSUE THREAD

**Issue by elhawaryna** [OpenVisionE2/openvision-oe#5]
ERROR: hostapd-2.6-r0 do_compile: Function failed: do_compile (log file is located at /home/elhawary/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/temp/log.do_compile.7517)
ERROR: Logfile of failure stored in: /home/elhawary/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/temp/log.do_compile.7517

**Comment by elhawaryna** [comment]
RROR: hostapd-2.6-r0 do_compile: Function failed: do_compile (log file is located at /home/elhawary/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/temp/log.do_compile.7517)
ERROR: Logfile of failure stored in: /home/elhawary/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/temp/log.do_compile.7517
Log data follows:
| DEBUG: Executing shell function do_compile
| make: pkg-config: Command not found
| make: pkg-config: Command not found
| make: pkg-config: Command not found
| make: pkg-config: Command not found
| ../src/drivers/driver_nl80211.c: In function 'family_handler':
| ../src/drivers/driver_nl80211.c:404:10: error: 'CTRL_ATTR_MCAST_GROUPS' undeclared (first use in this function)
|   if (!tb[CTRL_ATTR_MCAST_GROUPS])
|           ^~~~~~~~~~~~~~~~~~~~~~
| ../src/drivers/driver_nl80211.c:404:10: note: each undeclared identifier is reported only once for each function it appears in
| In file included from /home/elhawary/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/recipe-sysroot/usr/include/libnl3/netlink/msg.h:17:0,
|                  from /home/elhawary/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/recipe-sysroot/usr/include/libnl3/netlink/genl/genl.h:16,
|                  from ../src/drivers/driver_nl80211.c:17:
| /home/elhawary/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/recipe-sysroot/usr/include/libnl3/netlink/attr.h:275:26: warning: left-hand operand of comma expression has no effect [-Wunused-value]
|   for (pos = nla_data(nla), rem = nla_len(nla); \
|                           ^
| ../src/drivers/driver_nl80211.c:407:2: note: in expansion of macro 'nla_for_each_nested'
|   nla_for_each_nested(mcgrp, tb[CTRL_ATTR_MCAST_GROUPS], i) {
|   ^~~~~~~~~~~~~~~~~~~
| ../src/drivers/driver_nl80211.c:408:22: error: 'CTRL_ATTR_MCAST_GRP_MAX' undeclared (first use in this function)
|    struct nlattr *tb2[CTRL_ATTR_MCAST_GRP_MAX + 1];
|                       ^~~~~~~~~~~~~~~~~~~~~~~
| ../src/drivers/driver_nl80211.c:411:12: error: 'CTRL_ATTR_MCAST_GRP_NAME' undeclared (first use in this function)
|    if (!tb2[CTRL_ATTR_MCAST_GRP_NAME] ||
|             ^~~~~~~~~~~~~~~~~~~~~~~~
| ../src/drivers/driver_nl80211.c:412:12: error: 'CTRL_ATTR_MCAST_GRP_ID' undeclared (first use in this function)
|        !tb2[CTRL_ATTR_MCAST_GRP_ID] ||
|             ^~~~~~~~~~~~~~~~~~~~~~
| ../src/drivers/driver_nl80211.c:408:18: warning: unused variable 'tb2' [-Wunused-variable]
|    struct nlattr *tb2[CTRL_ATTR_MCAST_GRP_MAX + 1];
|                   ^~~
| make: *** [Makefile:1036: ../src/drivers/driver_nl80211.o] Error 1
| WARNING: /home/elhawary/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/temp/run.do_compile.7517:1 exit 2 from 'make'
| ERROR: Function failed: do_compile (log file is located at /home/elhawary/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/temp/log.do_compile.7517)
ERROR: Task (/home/elhawary/openvision-oe/meta-openembedded/meta-oe/recipes-connectivity/hostapd/hostapd_2.6.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4592 tasks of which 4568 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/openvision-oe/meta-openembedded/meta-oe/recipes-connectivity/hostapd/hostapd_2.6.bb:do_compile
Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:74: image] Error 1

Done, the compiled image is in build/tmp/deploy/images/ folder!
It's a zipped file like openvision-enigma2-develop-english|multilanguage|extrala

**Comment by persianpros** [comment]
Please follow the issue template.

**Comment by elhawaryna** [comment]
Where can I find the issue template, please, I'm new here

**Comment by persianpros** [comment]
@elhawaryna 

dm800 build should be fine now ;)
