### ISSUE TITLE
dm500hd build feed :  rtl8812au-5.1.5-r0 do_compile: oe_runmake failed

### ISSUE THREAD

**Issue by ycf83** [OpenVisionE2/openvision-oe#50]
hi,

error build feed dm500hd:

Initialising tasks: 100% |#######################################################################################################################################################################################| Time: 0:00:27
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: When reparsing /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 7c917573c7eae3bbf276da2d5a16d472 to 0ae6e0443f9e985cab9585823c275e0c. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 7c917573c7eae3bbf276da2d5a16d472 to 0ae6e0443f9e985cab9585823c275e0c. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 7c917573c7eae3bbf276da2d5a16d472 to 0ae6e0443f9e985cab9585823c275e0c. The metadata is not deterministic and this needs to be fixed.
ERROR: openvision-version-info-7.0-r4 do_install: Taskhash mismatch de750c32efed9287840165fa835a92dd versus bdd4c617dfb574eb1224815af8a3337e for /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install
ERROR: Taskhash mismatch de750c32efed9287840165fa835a92dd versus bdd4c617dfb574eb1224815af8a3337e for /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install
ERROR: When reparsing /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 7c917573c7eae3bbf276da2d5a16d472 to 0ae6e0443f9e985cab9585823c275e0c. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 7c917573c7eae3bbf276da2d5a16d472 to 0ae6e0443f9e985cab9585823c275e0c. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 7c917573c7eae3bbf276da2d5a16d472 to 0ae6e0443f9e985cab9585823c275e0c. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 7c917573c7eae3bbf276da2d5a16d472 to 0ae6e0443f9e985cab9585823c275e0c. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 7c917573c7eae3bbf276da2d5a16d472 to 0ae6e0443f9e985cab9585823c275e0c. The metadata is not deterministic and this needs to be fixed.
ERROR: When reparsing /home/d-ina/OpenPLI/openpli-oe-core/openvision-oe/recipes-openvision/openvision-version-info/openvision-version-info.bb.do_install, the basehash value changed from 7c917573c7eae3bbf276da2d5a16d472 to 0ae6e0443f9e985cab9585823c275e0c. The metadata is not deterministic and this needs to be fixed.
ERROR: rtl8189es-1.0-r0 do_compile: oe_runmake failed
ERROR: rtl8189es-1.0-r0 do_compile: Function failed: do_compile (log file is located at /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/temp/log.do_compile.31078)
ERROR: Logfile of failure stored in: /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/temp/log.do_compile.31078
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4 LINUX_SRC=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KDIR=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KSRC=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source M={D}/lib/modules/3.2-dm500hd/kernel/drivers/net/wireless KERNEL_SOURCE=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source LINUX_SRC=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KDIR=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KERNDIR=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KSRC=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KERNEL_VERSION=3.2-dm500hd KVER=3.2-dm500hd CC=mipsel-oe-linux-gcc  -fuse-ld=bfd AR=mipsel-oe-linux-ar  LD=mipsel-oe-linux-ld.bfd
| ERROR: oe_runmake failed
| make ARCH=mips CROSS_COMPILE=mipsel-oe-linux- -C /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source M=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux  modules
| make[1]: Entering directory '/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source'
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_cmd.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_security.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_debug.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_io.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_ioctl_query.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_ioctl_set.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_ieee80211.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_mlme.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_mlme_ext.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_wlan_util.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_vht.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_pwrctrl.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_rf.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_recv.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_sta_mgt.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_ap.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_xmit.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_p2p.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_tdls.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_br_ext.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_iol.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_sreset.o
| /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_iol.c: In function 'rtw_IOL_cmd_buf_dump':
| /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_iol.c:261:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
|    if(j%32 ==0) printk("\n");j++;
|    ^~
| /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_iol.c:261:29: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
|    if(j%32 ==0) printk("\n");j++;
|                              ^
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_btcoex.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_beamforming.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/rtw_odm.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/core/efuse/rtw_efuse.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/osdep_service.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/os_intfs.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/sdio_intf.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/sdio_ops_linux.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/ioctl_linux.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/xmit_linux.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/mlme_linux.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/recv_linux.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/ioctl_cfg80211.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/rtw_cfgvendor.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/wifi_regd.o
| /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/ioctl_cfg80211.c:35:32: fatal error: uapi/linux/nl80211.h: No such file or directory
|  #include <uapi/linux/nl80211.h>
|                                 ^
| compilation terminated.
| make[3]: *** [/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source/scripts/Makefile.build:305: /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux/os_dep/linux/ioctl_cfg80211.o] Error 1
| make[3]: *** Waiting for unfinished jobs....
| make[2]: *** [/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source/Makefile:1367: _module_/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/rtl8189ES_linux] Error 2
| make[1]: *** [Makefile:130: sub-make] Error 2
| make[1]: Leaving directory '/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source'
| make: *** [Makefile:1640: modules] Error 2
| WARNING: /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/temp/run.do_compile.31078:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8189es/1.0-r0/temp/log.do_compile.31078)
ERROR: Task (/home/d-ina/OpenPLI/openpli-oe-core/meta-openpli/recipes-connectivity/realtek/rtl8189es_1.0.bb:do_compile) failed with exit code '1'
ERROR: rtl8812au-5.1.5-r0 do_compile: oe_runmake failed
ERROR: rtl8812au-5.1.5-r0 do_compile: Function failed: do_compile (log file is located at /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/temp/log.do_compile.32486)
ERROR: Logfile of failure stored in: /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/temp/log.do_compile.32486
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4 LINUX_SRC=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KDIR=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source M={D}/lib/modules/3.2-dm500hd/kernel/drivers/net/wireless KERNEL_SOURCE=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source LINUX_SRC=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KDIR=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KERNDIR=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KSRC=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source KERNEL_VERSION=3.2-dm500hd KVER=3.2-dm500hd CC=mipsel-oe-linux-gcc  -fuse-ld=bfd AR=mipsel-oe-linux-ar  LD=mipsel-oe-linux-ld.bfd
| ERROR: oe_runmake failed
| make ARCH=mips CROSS_COMPILE=mipsel-oe-linux- -C /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source M=/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU  modules
| make[1]: Entering directory '/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source'
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU/os_dep/linux/ioctl_cfg80211.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU/hal/hal_com.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU/hal/hal_com_phycfg.o
|   CC [M]  /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU/hal/hal_phy.o
| /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU/os_dep/linux/ioctl_cfg80211.c:6083:68: warning: 'struct ieee80211_sta_vht_cap' declared inside parameter list will not be visible outside of this definition or declaration
|  static void rtw_cfg80211_init_vht_capab(_adapter *padapter, struct ieee80211_sta_vht_cap *vht_cap, u8 rf_type)
|                                                                     ^~~~~~~~~~~~~~~~~~~~~
| /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU/os_dep/linux/ioctl_cfg80211.c: In function 'rtw_cfg80211_init_vht_capab':
| /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU/os_dep/linux/ioctl_cfg80211.c:6092:9: error: dereferencing pointer to incomplete type 'struct ieee80211_sta_vht_cap'
|   vht_cap->vht_supported = _TRUE;
|          ^~
| /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU/os_dep/linux/ioctl_cfg80211.c: In function 'rtw_cfg80211_init_wiphy':
| /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU/os_dep/linux/ioctl_cfg80211.c:6218:48: error: 'struct ieee80211_supported_band' has no member named 'vht_cap'; did you mean 'ht_cap'?
|     rtw_cfg80211_init_vht_capab(padapter, &bands->vht_cap, rf_type);
|                                                 ^~
| make[3]: *** [/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source/scripts/Makefile.build:305: /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU/os_dep/linux/ioctl_cfg80211.o] Error 1
| make[3]: *** Waiting for unfinished jobs....
| make[2]: *** [/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source/Makefile:1367: _module_/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/rtl8812AU] Error 2
| make[1]: *** [Makefile:130: sub-make] Error 2
| make[1]: Leaving directory '/home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work-shared/dm500hd/kernel-source'
| make: *** [Makefile:1838: modules] Error 2
| WARNING: /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/temp/run.do_compile.32486:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at /home/d-ina/OpenPLI/openpli-oe-core/build/tmp/work/dm500hd-oe-linux/rtl8812au/5.1.5-r0/temp/log.do_compile.32486)
ERROR: Task (/home/d-ina/OpenPLI/openpli-oe-core/meta-openpli/recipes-connectivity/realtek/rtl8812au_5.1.5.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 7009 tasks of which 6978 didn't need to be rerun and 2 failed.

Summary: 2 tasks failed:
  /home/d-ina/OpenPLI/openpli-oe-core/meta-openpli/recipes-connectivity/realtek/rtl8189es_1.0.bb:do_compile
  /home/d-ina/OpenPLI/openpli-oe-core/meta-openpli/recipes-connectivity/realtek/rtl8812au_5.1.5.bb:do_compile
Summary: There were 15 WARNING messages shown.
Summary: There were 15 ERROR messages shown, returning a non-zero exit code.
make: *** [Makefile:130: feed] Error 1

**Comment by persianpros** [comment]
I know about this, tomorrow I'm going to work on it.
