### ISSUE TITLE
LCD does not work on mbultra.

### ISSUE THREAD

**Issue by Nemcio** [OpenVisionE2/openvision-oe#54]
The display on the mbultra LCD does not work. There is a black display. On other distributions of Opneatv, Egami, Hyperion Opendroid works.
3 months ago I compiled OpenPli and the display did not work either. The same symptoms are at OpenVision on OpenPli.

**Comment by persianpros** [comment]
I think the support is in their enigma2 and as OE-A teams are using different fork of PLi's enigma2, I have no idea where to look for this ...

Maybe you could dig it yourself: https://github.com/openatv/enigma2

**Comment by Nemcio** [comment]
LCD support is available in all distributions that support mbultra. It's not just in Openvision. No display skin and initialization and in the options menu.

**Comment by persianpros** [comment]
All of them are using a different fork of PLi (like OpenATV's enigma2) and we're using PLi's enigma2.

I can't search for you as this is not our priority, sorry.

But as I said you could dig their sources or ask them for the code and point us there.

**Comment by Nemcio** [comment]
Is openvision in?
https://github.com/oe-alliance/enigma2-display-skins
Mbultra uses display255.
The issue is to adapt it to openvision and add a function.

**Comment by persianpros** [comment]
Yeah we don't have display-skins but we should have them ...

**Comment by Nemcio** [comment]
You also need to add the skin selector option:
![opena1a](https://user-images.githubusercontent.com/2566039/51790965-769b1300-219c-11e9-8020-a7cc56d5ec38.jpg)
Skins selection options:
![opena4a](https://user-images.githubusercontent.com/2566039/51790978-a1856700-219c-11e9-9739-ba9c50f7a519.jpg)
And initialization at startup.
This option will also be useful for other stb models.
If you need to check and test it, I can compile and test the correctness of operation on mbultra.

**Comment by persianpros** [comment]
This will be on our feeds: https://github.com/OpenVisionE2/openvision-oe/commit/83b62e750a5293586d16794c8d801dbfde8a46c9

But it's not enough as the main changes are in enigma2 itself ...

**Comment by persianpros** [comment]
Ok now we have display skins in enigma2: https://github.com/OpenVisionE2/openvision-oe/commit/19994ef3263a52b74ef812687a281dbb6125eb1f

But no "Display settings" as this should be adapted for PLi's enigma2 and I don't have time for it, I will close this for now, test our images after r5 release and open a new issue if it wasn't ok.
