### ISSUE TITLE
sparkvfd plugin error

### ISSUE THREAD

**Issue by ahmedmoselhi** [OpenVisionE2/openvision-oe#6]
i got this error while running enigma2 from telnet:
PYTHONPATH: /usr/lib/enigma2/python
DVB_API_VERSION 5 DVB_API_VERSION_MINOR 10
ENIGMA_DEBUG_LVL=3

[MAIN] executing main

close failed in file object destructor:
IOError: [Errno 5] Input/output error

close failed in file object destructor:
IOError: [Errno 14] Bad address
close failed in file object destructor:
IOError: [Errno 14] Bad address
close failed in file object destructor:
IOError: [Errno 14] Bad address
close failed in file object destructor:
IOError: [Errno 14] Bad address
close failed in file object destructor:
IOError: [Errno 5] Input/output error

Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SparkVFDControl/plugin.py", line 146, in vrime

    self.__eventInfoChanged()
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SparkVFDControl/plugin.py", line 78, in __eventInfoChanged
    vfd_write(name)
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/SparkVFDControl/plugin.py", line 35, in vfd_write
    open("/dev/dbox/oled0", "w").write(text)
IOError: [Errno 2] No such file or directory: '/dev/dbox/oled0'

Killed

**Comment by persianpros** [comment]
Open Vision r7 is out, please test our official release and let us know if there's a crash.

**Comment by tail1** [comment]
Hi buddy, what happened to the forum? It does not let me.


>Четверг, 14 февраля 2019, 12:18 +03:00 от Persian Prince <notifications@github.com>:
>
>Closed  #6 .
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Dmitry N.

**Comment by persianpros** [comment]
The forum domain changed to forum.openvision.tech therefor if you're having problems logging in, make sure to delete your browser cache/cookies/history first!
