### ISSUE TITLE
pkg-config: Command not found+drivers+hostapd

### ISSUE THREAD

**Issue by menuf** [OpenVisionE2/openvision-oe#6]
DEBUG: Executing shell function do_compile
make: pkg-config: Command not found
make: pkg-config: Command not found
make: pkg-config: Command not found
make: pkg-config: Command not found
../src/drivers/driver_nl80211.c: In function 'family_handler':
../src/drivers/driver_nl80211.c:404:10: error: 'CTRL_ATTR_MCAST_GROUPS' undeclared (first use in this function)
  if (!tb[CTRL_ATTR_MCAST_GROUPS])
          ^~~~~~~~~~~~~~~~~~~~~~
../src/drivers/driver_nl80211.c:404:10: note: each undeclared identifier is reported only once for each function it appears in
In file included from /home/dellegy/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/recipe-sysroot/usr/include/libnl3/netlink/msg.h:17:0,
                 from /home/dellegy/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/recipe-sysroot/usr/include/libnl3/netlink/genl/genl.h:16,
                 from ../src/drivers/driver_nl80211.c:17:
/home/dellegy/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/recipe-sysroot/usr/include/libnl3/netlink/attr.h:275:26: warning: left-hand operand of comma expression has no effect [-Wunused-value]
  for (pos = nla_data(nla), rem = nla_len(nla); \
                          ^
../src/drivers/driver_nl80211.c:407:2: note: in expansion of macro 'nla_for_each_nested'
  nla_for_each_nested(mcgrp, tb[CTRL_ATTR_MCAST_GROUPS], i) {
  ^~~~~~~~~~~~~~~~~~~
../src/drivers/driver_nl80211.c:408:22: error: 'CTRL_ATTR_MCAST_GRP_MAX' undeclared (first use in this function)
   struct nlattr *tb2[CTRL_ATTR_MCAST_GRP_MAX + 1];
                      ^~~~~~~~~~~~~~~~~~~~~~~
../src/drivers/driver_nl80211.c:411:12: error: 'CTRL_ATTR_MCAST_GRP_NAME' undeclared (first use in this function)
   if (!tb2[CTRL_ATTR_MCAST_GRP_NAME] ||
            ^~~~~~~~~~~~~~~~~~~~~~~~
../src/drivers/driver_nl80211.c:412:12: error: 'CTRL_ATTR_MCAST_GRP_ID' undeclared (first use in this function)
       !tb2[CTRL_ATTR_MCAST_GRP_ID] ||
            ^~~~~~~~~~~~~~~~~~~~~~
../src/drivers/driver_nl80211.c:408:18: warning: unused variable 'tb2' [-Wunused-variable]
   struct nlattr *tb2[CTRL_ATTR_MCAST_GRP_MAX + 1];
                  ^~~
Makefile:1036: recipe for target '../src/drivers/driver_nl80211.o' failed
make: *** [../src/drivers/driver_nl80211.o] Error 1
WARNING: /dellegy/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/temp/run.do_compile.14223:1 exit 2 from 'make'
ERROR: Function failed: do_compile (log file is located at /home/dellegy/openvision-oe/build/tmp/work/mips32el-nf-oe-linux/hostapd/2.6-r0/temp/log.do_compile.14223)

**Comment by persianpros** [comment]
Please follow issue template and post your problem again.

**Comment by elhawaryna** [comment]
Where can I find the issue template, please, I'm new here
