### ISSUE TITLE
wetekplay crash on first start

### ISSUE THREAD

**Issue by yoyanozovi** [OpenVisionE2/openvision-oe#60]
The first start on a wetekplay crashed with this message:

**We are really sorry. Your STB encountered a software problem and needs to be restarted.
Please send the log file /tmp/enigma2_crash.log to crash@openvision.tech
Your STB restarts in 10 seconds!
Component: Enigma2**

It was the image openvision-enigma2-develop-7.0-r3-wetekplay.img from 17.01.2019 11:45.
Console output: [openvision-enigma2-develop-7.0-r3-wetekplay_Install_1.log](https://github.com/OpenVisionE2/openvision-oe/files/2798859/openvision-enigma2-develop-7.0-r3-wetekplay_Install_1.log)

**Comment by persianpros** [comment]
Hi,

Yeah we know about this, please wait for r5 release.
