### ISSUE TITLE
dm500hd :oscam-emu & oscam removed from feed

### ISSUE THREAD

**Issue by ycf83** [OpenVisionE2/openvision-oe#66]
hi, 

in the previous open vision version, we have oscam-emu  in feed ,  now it's removed , so can u please add it back to dreambox 500hd , we need it to open scrambled channel with softcam ; 

also i don't find normal oscam too .

PS: i build feed at home like image.

thnk's

![oscam](https://user-images.githubusercontent.com/39797567/51806040-38bded80-2275-11e9-8626-97d8d1151dc8.jpg)

**Comment by persianpros** [comment]
Fixed: https://github.com/OpenVisionE2/openvision-oe/commit/c77ac4da52d763af44c9b14b6b399f8f29211e6a
