### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by moksy386** [OpenVisionE2/openvision-oe#7]
I want to try openvision for my stb & i've never compiled befor
I see commits on this repo but no documentation or no support & no image release to download
Even in your forum there is no body so I'm asking is this project dead ? or is there any other ressource documentation or whatever where i can get help to get image for my dreambox 520 ?

**Comment by persianpros** [comment]
How a project could be dead when it gets daily updates?

Do we know what are you doing exactly that you get too many weird errors which we don't have? Keep in mind fetch errors are not related to us as you may don't have access to some IPs in your country.

README.md file contains what you need if you're using Ubuntu 18.04.x LTS (native).

We don't provide releases for now but we support what we have, there is a private section and most of our discussions are there.

If you mean https://forum.openvision.tech/viewtopic.php?f=6&t=422 nobody reacted because you have fetch errors which is not related to us, when you can't access github how it can be our problem?

**Comment by moksy386** [comment]
I didn't mean to offence sir I was just frustrated because build took me long time and i am new as i said i've never complide before.
I am on virtual machine, when you say native do you mean it doesn"t compile on vm ? thanks

**Comment by moksy386** [comment]
And what i meant by saying dead is that there is no interaction on this repo, it's important to get help, for sure I am newbie, if you don't accept newbie questions sorry for that, if it was stated I'd not asked for help. Thanks anyway and sorry to bother you

**Comment by persianpros** [comment]
It's ok :)

We're not sure about VM because we use native but I think you're getting those errors because you're using on VM.

**Comment by moksy386** [comment]
Many thanks sir now i've installed Ubuntu Native and here are a bunch of errors may be you can help me:

`ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/x/xterm-256color pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/x/xterm-256color. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/x/xterm-color pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/x/xterm-color. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/x/xterm-xfree86 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/x/xterm-xfree86. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/s/screen pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/s/screen. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/s/screen-256color pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/s/screen-256color. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/s/sun pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/s/sun. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/l/linux pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/l/linux. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/r/rxvt pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/r/rxvt. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/a/ansi pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/a/ansi. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt220 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt220. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt102 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt102. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt200 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt200. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt52 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt52. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt100 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt100. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/d/dumb pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/d/dumb. Please replace this with a relative link
`
