### ISSUE TITLE
dabstreamer need missing depend package ..

### ISSUE THREAD

**Issue by fairbird** [OpenVisionE2/openvision-oe#76]
This commit
https://github.com/OpenVisionE2/openvision-oe/commit/34073f8a5acb01355c041b3fc5fe9b4fb362fe50
missing (tsniv2ni)

> ERROR: Nothing RPROVIDES 'tsniv2ni' (but /home/raed/build_image/920-BlackHole/openpli-oe-core/OpenVisionE2/recipes-devtools/python/dabstreamer.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'tsniv2ni' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['tsniv2ni']
ERROR: Required build target 'dabstreamer' has no buildable providers.
Missing or unbuildable dependency chain was: ['dabstreamer', 'tsniv2ni']

**Comment by persianpros** [comment]
Fixed: https://github.com/OpenVisionE2/openvision-oe/commit/4ad957a95652f8f06f43c7895fefbbec44b04802

Thanks for the report :+1:
