### ISSUE TITLE
ERROR ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink

### ISSUE THREAD

**Issue by moksy386** [OpenVisionE2/openvision-oe#8]
Many thanks sir now i've installed Ubuntu Native and here are a bunch of errors may be you can help me:

**ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink** /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/x/xterm-256color pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/x/xterm-256color. **Please replace this with a relative link.**
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/x/xterm-color pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/x/xterm-color. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/x/xterm-xfree86 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/x/xterm-xfree86. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/s/screen pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/s/screen. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/s/screen-256color pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/s/screen-256color. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/s/sun pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/s/sun. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/l/linux pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/l/linux. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/r/rxvt pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/r/rxvt. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/a/ansi pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/a/ansi. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt220 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt220. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt102 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt102. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt200 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt200. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt52 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt52. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/v/vt100 pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/v/vt100. Please replace this with a relative link.
ERROR: ncurses-native-6.0+20171125-r0 do_populate_sysroot: sstate found an absolute path symlink /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/sysroot-destdir/home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/usr/share/terminfo/d/dumb pointing at /home/mok/Openvision/openpli-oe-core/build/tmp/work/x86_64-linux/ncurses-native/6.0+20171125-r0/recipe-sysroot-native/etc/terminfo/d/dumb. Please replace this with a relative link

**Comment by shmoxy75** [comment]
I've compiled it finally and installed it many thanks to all team

**Comment by persianpros** [comment]
@shmoxy75 

Don't forget to donate if you like Open Vision :+1:

**Comment by shmoxy75** [comment]
Yes as soon as i get a credit card i promiss & when i distribute final build i'l allways give credits & link to your homepage or github as you like :)

**Comment by petrkr** [comment]
> I've compiled it finally and installed it many thanks to all team

post solution for this would help... I have now same problem. Used google to find your super commet "it compiled finally" BUT you forgot post solution...
