### ISSUE TITLE
mediafire

### ISSUE THREAD

**Issue by persianpros** [OpenVisionE2/openvision-oe#8]
@Hains @moham96 @MastaG @milaebrothers @kueken 

Hello my friends,

As I used this link: https://www.mediafire.com/folder/p0hyt9w5cq4d9/pli-extras everywhere for all brands/models if you want to upload your compiled test images on it just let me know and write your email address so I could send you the login details ;)

**Comment by MastaG** [comment]
@Hains @moham96 @MastaG @milaebrothers @kueken
I've setup a build server on my home server and I've rented a cheap VPS for hosting a forum and downloads.
My build server:
CPU: Intel Xeon(R) E3-1265L V2
RAM: 16GB
Storage: 4x4TB RAID-5
Builds aren't going to be produced very fast as there's no SSD's.
If someone else would like to volunteer for setting up a build server, please let us know :)

The VPS will host openvision.tech.
So I still need:
- Forum software (so we can stop chatting here)
- Forum admins
- A vision bootlogo @Hains ?

If someone knows some good free forum which can run on nginx/mysql let me know.
I hope to have everything ready before the end of the year.

**Comment by MastaG** [comment]
So thanks to @Hains and Taapat for looking into the glibc 2.28 issues, I can now build images on my Fedora 29 server.

I've successfully built a spark7162, dm800 and dm800se image, I guess those are the hardest ones.
For the record images are built from a clean checkout of openpli-oe-core and pli-extras.
I only run update.sh prior to build.
There are no local (uncommitted) changes at all.
I've only set a feed url in my local.conf.

I'm planning to build all machines and then upload the images and feeds for public consumption.

If there's any tips or feedback please let me know.

Btw.. we still need a proper Vision logo because they now boot with:
This is a homebuild image based on OpenPLI ;)

Also please let me know some ideas for a forum, if you guys don't like the idea for a dedicated forum, then that's fine by me as well.
Don't mean to push anyone here..

**Comment by MastaG** [comment]
btw, there's many receivers I haven't had a part in, like azboxhd for example:
Build Configuration:
BB_VERSION        = "1.34.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "fedora-29"
TARGET_SYS        = "mipsel-oe-linux"
MACHINE           = "azboxhd"
DISTRO            = "openpli"
DISTRO_VERSION    = "pli-extras"
TUNE_FEATURES     = "o32 fpu-hard mips32"
TARGET_FPU        = ""
meta-oe
meta-filesystems
meta-multimedia
meta-networking
meta-python
meta-webserver    = "HEAD:dfbdd28d206a74bf264c2f7ee0f7b3e5af587796"
meta              = "HEAD:93dd2f9f3edf0584f9e806c629611d645dd72dbf"
meta-openpli      = "develop:cc426819360deda1e39233e4aca2af6f752e5a0e"
meta-vuplus       = "HEAD:d6f0477dc48bad742290f588efd4d9da604cfb29"
meta-xsarius.pli5 = "HEAD:d78a86d09b48311028ea41586ee3f4165d119390"
meta-qviart       = "HEAD:d06277aec16586f846a09b8a9d58d6fbc895db63"
meta-xp           = "HEAD:2f818d2ee1efbf0a4536d8384d716a0767cf7039"
meta-xtrend       = "HEAD:ac054abbe235f33f6a69e7a8ff0fa9a7efa84f59"
meta-formuler     = "HEAD:e1d33c48edb119dcc3163855b0b1af510912ef52"
meta-gfutures     = "HEAD:18fc1d39a004358346311809abcbc3358eb77683"
meta-xpeedc       = "HEAD:f12908a5573de8a6a06ad9f75081846a590511c4"
meta-zgemma       = "HEAD:6bf7216a2891c6779187c1d798d8d098f2d81f6f"
meta-edision      = "HEAD:013c13f94c9c7e4e12b609c7b7fabfa085f450b9"
meta-miraclebox   = "HEAD:d44871d4d1f357d5b38488ed505b48fa8c8feff3"
meta-spycat       = "HEAD:a19f11bbcdcad969e9f6f8d2c30df0653427d4cb"
meta-gi           = "HEAD:01fd1e8256f53d40371e65514e13a53ef53e400d"
meta-sab          = "HEAD:92262feb14e4005c8096150daac7313e9cb3d85a"
meta-gigablue     = "HEAD:7e437da8e19274143229f2c52e62917cb33d9d1c"
meta-amiko        = "HEAD:b6416ddfc6130265e0b3054d144b96b59fdf7a03"
meta-axasuhd      = "HEAD:dfc1465665f504fdc4d6fc9a401e630b04123211"
meta-local        = "develop:cc426819360deda1e39233e4aca2af6f752e5a0e"
meta-qt5          = "HEAD:c6aa602d0640040b470ee81de39726276ddc0ea3"
meta-ax           = "HEAD:d05194b8f2794de8ca1f03851a7fde1400db8ffc"
meta-azbox        = "HEAD:04ffbdd0afc7da134fb620f9edb5c56eb1607a18"
meta-blackbox     = "HEAD:ef54a26c8be6fe135dad54deb7f1421dfc475fbc"
meta-broadmedia   = "HEAD:c2e7ba19cf2454211cfd5dcb87697f579e11cf37"
meta-ceryon       = "HEAD:a404828375ecb5d0f36bd55bbab61cda1cd2d374"
meta-clap         = "HEAD:b9bdbbecdc0f2dab3639367beaa4e393b029aa50"
meta-cube         = "HEAD:36a80488ab79fc61ae7dd8fb05e9ecf4c011a299"
meta-dags         = "HEAD:0741fe49560e0c1f5977d4b7d46f29e9b8ceebcd"
meta-dinobot      = "HEAD:2dc291c4d95cc985d963948901371e7f60916692"
meta-dream        = "HEAD:1c152335e1991bfb4900449e5d0f05e933441b06"
meta-ebox         = "HEAD:c171db6798e9d9a3c472ca1ce3878852022e1404"
meta-entwopia     = "HEAD:c43d8cb480fc2569995ba665810837580a6b30ba"
meta-fulan        = "HEAD:b4e15ba82d91b66d2c1b2070a585f88e59daf3c9"
meta-gb           = "HEAD:e2fc1749bc85b62f1982c3b2cac97aee35daf635"
meta-hypercube    = "HEAD:aa135c99576a949d5f0c9ed2e289fec48f597781"
meta-ini          = "HEAD:8b33da9634aec53321f426cedd6d0f679f1972ab"
meta-ixuss        = "HEAD:c6fa9c62fef35b6059faf1cf040ccb3d348d6916"
meta-linkdroid    = "HEAD:62a3a708e4001894915af3a4060e9376530102df"
meta-minix        = "HEAD:523180976e3eb73def124971c43d1f47e664b41e"
meta-octagon      = "HEAD:5056a67da9e5a04a808282314b36904d77aaa24e"
meta-odin         = "HEAD:61e888e1df903a77ad181ee02b960263322826a5"
meta-odroid       = "HEAD:839fd7cc211bc97ace3140942d3e9e29a0f6a745"
meta-protek       = "HEAD:c7e6f9640bbf9e8a0c9a2a15d1cc2c71c4806a05"
meta-raspberrypi  = "HEAD:2fe7203aad8534c51380d74bce46cf9b8e5df955"
meta-tiviar       = "HEAD:1eb5a8ebf58f6c09fbaee14d01ee77f63bc2f871"
meta-tripledot    = "HEAD:92207d30300c653249849fe761419f352480b938"
meta-uclan        = "HEAD:f2025c075adb3da0f45d68aae7af35cc52204652"
meta-wetek        = "HEAD:9243173dfd8508c675ca64fab3a14d074356b2ba"
meta-xcore        = "HEAD:de404ff2e713398067b734f184c198a3cf5f0a4a"
meta-xt           = "HEAD:d449885f319ae7f8f580db0c84a46eaed0f8c0b6"
pli-extras        = "develop:cdc2cea518331390c750d20b20c5d622bae507a6"

Initialising tasks: 100% |###########################################################################################################################################| Time: 0:00:06
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: glibc-initial-2.25-r0 do_patch: Command Error: 'quilt --quiltrc /media/data2/pcore/build/tmp/work/mips32el-oe-linux/glibc-initial/2.25-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0006-readlib-Add-OECORE_KNOWN_INTERPRETER_NAMES-to-known-.patch
can't find file to patch at input line 23
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 520cb9e746af637cf01fea385b7f4ee4aadbdfdd Mon Sep 17 00:00:00 2001
|From: Khem Raj <raj.khem@gmail.com>
|Date: Wed, 18 Mar 2015 00:11:22 +0000
|Subject: [PATCH 06/26] readlib: Add OECORE_KNOWN_INTERPRETER_NAMES to known
| names
|
|This bolts in a hook for OE to pass its own version of interpreter
|names into glibc especially for multilib case, where it differs from any
|other distros
|
|Upstream-Status: Inappropriate [OE specific]
|
|Signed-off-by: Lianhao Lu <lianhao.lu@intel.com>
|Signed-off-by: Khem Raj <raj.khem@gmail.com>
|---
| elf/readlib.c | 1 +
| 1 file changed, 1 insertion(+)
|
|diff --git a/elf/readlib.c b/elf/readlib.c
|index 8a66ffe..08d56fc 100644
|--- a/elf/readlib.c
|+++ b/elf/readlib.c
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Patch 0006-readlib-Add-OECORE_KNOWN_INTERPRETER_NAMES-to-known-.patch does not apply (enforce with -f)
ERROR: glibc-initial-2.25-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /media/data2/pcore/build/tmp/work/mips32el-oe-linux/glibc-initial/2.25-r0/temp/log.do_patch.3289
ERROR: Task (/media/data2/pcore/openembedded-core/meta/recipes-core/glibc/glibc-initial_2.25.bb:do_patch) failed with exit code '1'

**Comment by MastaG** [comment]
http://source.mynonpublic.com/azbox/initramfs-azboxhd-oe-core-3.9.2-16092013.tar.bz2
Can somebody upload initramfs-azboxhd-oe-core-3.9.2-16092013.tar.bz2 for me?
The file was removed from the mirror I guess. Funny because oe-alliace-core is also pointing to this file in their recipe:
https://github.com/oe-alliance/oe-alliance-core/blob/39a6a6f104230aaf3c3018a29eae43e37132f2b5/meta-brands/meta-azbox/recipes-linux/linux-azbox_3.9.2.bb#L40

**Comment by MastaG** [comment]
Fixed azboxhd for now: https://github.com/PLi-metas/meta-azbox/commit/5eb3b79783fc46ca52c4bcf3a5df9b5d443c9a56
I hope to find somebody who can test it.

**Comment by persianpros** [comment]
I have all the sources for all brands/models even azbox, if you need something just let me know ;)

**Comment by persianpros** [comment]
azbox.zip:
azboxhd-dvb-modules-3.9.2-opensat-oe-core-19092013.tar.gz
azboxme-dvb-modules-3.9.2-opensat-oe-core-17092013.tar.gz
azboxminime-dvb-modules-3.9.2-opensat-oe-core-17092013.tar.gz
initramfs-azboxhd-oe-core-3.9.2-16092013.tar.bz2
initramfs-azboxme-oe-core-3.9.2-14092013.tar.bz2
initramfs-azboxminime-oe-core-3.9.2-14092013.tar.bz2

Download link: http://www.mediafire.com/file/o8xsvilqy4bmscg/azbox.zip/file

👍

**Comment by persianpros** [comment]
Regarding forum I mentioned earlier that I own vBulletin 4 Publishing Suite license and we could use it, it's not open source but it's stable and secure with so many features.

**Comment by persianpros** [comment]
@MastaG 
Yeah for all models you need more space :)

For Amlogic SoCs I did revert https://github.com/OpenPLi/enigma2/commit/545449c5a5a213438f0d614de29561fa34a7b6cf and that's the patch (which needs to be updated with latest enigma2 changes) but the real solution I think is to adapt the code for https://github.com/OpenPLi/enigma2/blob/develop/lib/dvb/amldecoder.cpp and https://github.com/OpenPLi/enigma2/blob/develop/lib/dvb/amldecoder.h

**Comment by persianpros** [comment]
@MastaG 
You can try my cleanup scrpit for some models: https://github.com/PLi-metas/pli-extras/blob/develop/cleanup.sh ;)

Regarding vBulletin, you can't download or install it when you don't have access to the license page and I need to do it myself also vBulletin 4.2.5 requires PHP 5.6.0+ and MySQL 5.5.8+.

**Comment by MastaG** [comment]
@persianpros 
Even better, then I'll grant you access :)
email me your pubilc key then I'll at the to the authorized keys.

**Comment by persianpros** [comment]
Take a look at https://forums.openpli.org/topic/57419-howto-build-unofficial-pli-for-your-unsupported-receiver/page-137 we're not allowed to provide Open PLi images so only Open Vision, since now please only focus on Open Vision and don't provide any Open PLi test images. All Open PLi test images on my mediafire have been deleted.

**Comment by MastaG** [comment]
Yes, my buildserver only does vision-enigma2-feed..
But like I said we still need a bootlogo.. because the 'vision' bootlogo recipe, is just a copy of the OpenPLi homebuild.

Btw I'll prepare the last bits of the server this afternoon so you can go and install your forum.
Still have to setup dkim dns records.

**Comment by persianpros** [comment]
You could use this logo for now: http://www.mediafire.com/file/69c5fazmbidks0x/insite-vision-logo-png-transparent.zip/file

As we're not allowed to use Open PLi logo.

**Comment by Hains** [comment]
Yeah sorry MastaG i couldn't find a nice usefull bootlogo for now.
I'm busy with migration build server Zeros from openpli to openvision.

**Comment by persianpros** [comment]
I think PLi won't swtich to sumo anytime soon and it's possible that they skip it so in my opinion for now it's better to remove all sumo branches and don't work on them, focus on develop and if you want just keep those branches locally, if you have them locally please remove all sumo branches.

**Comment by Hains** [comment]
Yeah. No support, nobody cares about that branch(except one, but i told him 1000 times to use develop branch).
I'll delete them.

**Comment by Hains** [comment]
About recipe names, should we keep vision-xxxxx-xxxxx.bb or change it to openvision-xxxxxx-xxxxx.bb?

**Comment by persianpros** [comment]
We can do both, I myself don't care :)

**Comment by persianpros** [comment]
https://github.com/PLi-metas/pli-extras/blob/develop/recipes-openpli/enigma2/enigma2/openvision.patch should be updated again :( I don't have time for this now ...

**Comment by Hains** [comment]
I'm not either.
It's Christmas, so i'm leaving soon for dinner.
Tomorrow, you or me?

Great job BTW.

**Comment by Hains** [comment]
I noticed a warning about openweb interface, it's using openweb OpenPLi.
But perhaps it's solved with a build from scratch (build dir deleted),
Anyway, something for tomorrow.

**Comment by MastaG** [comment]
@Hains and @persianpros 
Thanks for the hard work!

**Comment by persianpros** [comment]
@Hains 
https://github.com/PLi-metas/pli-extras/blob/develop/recipes-openpli/enigma2/enigma2/openvision.patch needs to be updated.

For Amlogic SoCs I did revert https://github.com/OpenPLi/enigma2/commit/545449c5a5a213438f0d614de29561fa34a7b6cf and that's https://github.com/PLi-metas/meta-linkdroid/blob/develop/recipes-openpli/enigma2/enigma2/revert-gamma-changes.patch (which needs to be updated with latest enigma2 changes) but the real solution I think is to adapt the code for https://github.com/OpenPLi/enigma2/blob/develop/lib/dvb/amldecoder.cpp and https://github.com/OpenPLi/enigma2/blob/develop/lib/dvb/amldecoder.h

revert-gamma-changes.patch is present in some amlogic metas like linkdroid and odroid (I don't remember all of them) and without it those metas are unbuildable now, if you have time please update these patches.

Thanks in advance.

**Comment by persianpros** [comment]
@Hains 
If it's possible for you create a patch for https://github.com/OpenPLi/openpli-oe-core/pull/611 so they could use Backup Suite on sumo, please.

**Comment by Hains** [comment]
Yes later.

But i can't build any image anymore, due to layer.conf not found.
I clone from scratch, openpli-oe-core, pli-extras,
I remove submodule and clone again.
But then failure in other submodule.
 I give up..

**Comment by persianpros** [comment]
Hmm give me some time (I'm not home or at work right now) I'll check it tonight as the build is going ok with RPi3

**Comment by Hains** [comment]
It's OK now.

**Comment by persianpros** [comment]
Thanks :+1: 
It seems shallow git behaves differently on different systems ...

**Comment by persianpros** [comment]
Any good idea how to remove this huge font https://github.com/OpenPLi/enigma2/commit/ac0d34146f76cdfdb9363e6780424fd284743b68 for smallflash boxes using https://github.com/PLi-metas/pli-extras/blob/develop/recipes-openvision/images/openvision-enigma2-image.bb#L122 ?

**Comment by Hains** [comment]
The only way is to apply a patch for small flash boxes which revert that commit.
And a do_install_append with a -rm  <filename>- for those boxes.

I upload patch, hold on.

**Comment by persianpros** [comment]
I think we don't need to revert, we only need to remove that huge font ...

**Comment by Hains** [comment]
It's in the Makefile, so if you just remove it, before compilation, it breaks the build.
And after compilation it probably let the box crash, due to a missing file.

**Comment by Hains** [comment]
For everyone's information.

We can't use OpenPLi forum anymore to put test images and help users with build failures etc.
An own forum is now mandatory..
So for the time being (till we have a forum), we must can use github for test images and support only!

**Comment by persianpros** [comment]
Yes I saw the message and did reply.
The topic should be closed.
After our daily/weekly/monthly builds there will be no need to provide support regarding image building as we're compiling the images.

**Comment by engineerkhan15** [comment]
@persianpros 
I am trying to compile for k1pro on Ubuntu 18.04 LTS but when I enter "Linkdroid" as meta name when asked, I get an error "Not a valid answer!"

**Comment by persianpros** [comment]
@engineerkhan15 Fixed, update and test again 👍

**Comment by Hains** [comment]
@persianpros 

Do you need dreambox images for mediafire. I have a lot and i'm gonna build all of them if you need them.

**Comment by persianpros** [comment]
I just compiled for RPi, I think your recipes are not update, try update.sh then image.sh which is ok now.

**Comment by persianpros** [comment]
@Hains I'm waiting for @MastaG as he said he's compiling for all brands/models so I guess we don't need mediafire anymore?

**Comment by engineerkhan15** [comment]
Tried again after updating but again same error, some issue due to patching with openvision.patch:
`Initialising tasks: 100% |###################################################################################################################################################################| Time: 0:00:14
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: enigma2-2.7+gitAUTOINC+bdbb9d6def-r0 do_patch: Command Error: 'quilt --quiltrc /home/ek/openpli-oe-core/build/tmp/work/k1pro-oe-linux/enigma2/2.7+gitAUTOINC+bdbb9d6def-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch openvision.patch
patching file data/setup.xml
patching file lib/driver/hdmi_cec.cpp
patching file lib/python/Components/AVSwitch.py
patching file lib/python/Components/Network.py
patching file lib/python/Components/NimManager.py
Hunk #1 succeeded at 1573 (offset -1 lines).
Hunk #2 succeeded at 1581 (offset -1 lines).
Hunk #3 succeeded at 1589 (offset -1 lines).
patching file lib/python/Components/Sources/FrontendStatus.py
patching file lib/python/Components/UsageConfig.py
Hunk #7 FAILED at 215.
1 out of 8 hunks FAILED -- rejects in file lib/python/Components/UsageConfig.py
patching file lib/service/servicedvb.cpp
Patch openvision.patch does not apply (enforce with -f)
ERROR: enigma2-2.7+gitAUTOINC+bdbb9d6def-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/ek/openpli-oe-core/build/tmp/work/k1pro-oe-linux/enigma2/2.7+gitAUTOINC+bdbb9d6def-r0/temp/log.do_patch.24977
ERROR: Task (/home/ek/openpli-oe-core/meta-openpli/recipes-openpli/enigma2/enigma2.bb:do_patch) failed with exit code '1'
`

**Comment by persianpros** [comment]
@Hains Do you have a problem with openvision.patch like @engineerkhan15 ?

**Comment by Hains** [comment]
No, i rebased patch against latest enigma2 and it applies against all boxes.

**Comment by persianpros** [comment]
Yeah it's ok for me too, @engineerkhan15 remove pli-extras and clone it again.

**Comment by engineerkhan15** [comment]
Can it have some relation with the old sources files in sources folder? In fact, in order to save network data of my limited data package, I copied backup of my sources to the sources folder.

**Comment by persianpros** [comment]
No as the OE fetches new things itself.

**Comment by Hains** [comment]
Check file permission on read only. I noticed same problem when i copied backup sources from NAS to build servers.

**Comment by engineerkhan15** [comment]
@Hains Can you guide please, I have to check file permissions of which file?

**Comment by Hains** [comment]
openpli-oe-core/sources/github.com.OpenPLi.enigma2.git
openpli-oe-core/sources/github.com.OpenPLi.enigma2.git.done

**Comment by persianpros** [comment]
Please don't commit anything to pli-extras as I'm changing the names, I let you know when it's finished.
Thanks in advance.

**Comment by atvcaptain** [comment]
i wonder your clone all oe-a metas, not better help update oe-a and not working with a copy ?

**Comment by persianpros** [comment]
Done, Open Vision OE is ready now.

Remove "pli-extras" folder and do step 3: https://github.com/OpenVisionE2/openvision-oe#how-to-build-an-open-vision-image

**Comment by persianpros** [comment]
@atvcaptain We have more metas (PLi + OE-A + Vision) and more brands/models, For example we have RaspberryPi, MINIX, ... and our OE is not compatible with OE-A as we use Open PLi's OE as our base.

**Comment by persianpros** [comment]
image.sh now supports PLi's supported brands/models: https://github.com/OpenVisionE2/openvision-oe/blob/develop/PLi-metas.md

Test and let me know if it has any problem.
