### ISSUE TITLE
Where has the dm920 images gone?

### ISSUE THREAD

**Issue by lb5je** [OpenVisionE2/openvision-oe#80]
Can't find any Dream images at https://openvision.tech/stb-images/ , something wrong?

2pat

**Comment by lb5je** [comment]
Did try to compile one also, but get some error messages:
Seems "meta-fulan" is the problem


Synchronizing submodule url for 'meta-xt'
error: Server does not allow request for unadvertised object c9cc8569fcb61e4cd261264e29dcd7d510e672a2
Fetched in submodule path 'meta-fulan', but it did not contain c9cc8569fcb61e4cd261264e29dcd7d510e672a2. Direct fetching of that commit failed.

Done!

Already up to date.
Let us fix the image names ...

Done!

Check for dm7020hdv2 required changes ...

We need to modify Makefile ...
Done, now you can compile dm7020hdv2 image too.

Generating /home/hjstrandby/openpli-oe-core/build/env.source
Generating /home/hjstrandby/openpli-oe-core/build/conf/bblayers.conf
Updating Git repositories...
Already up to date.
Synchronizing submodule url for 'bitbake'
Synchronizing submodule url for 'meta-amiko'
Synchronizing submodule url for 'meta-axasuhd'
Synchronizing submodule url for 'meta-edision'
Synchronizing submodule url for 'meta-formuler'
Synchronizing submodule url for 'meta-gfutures'
Synchronizing submodule url for 'meta-gi'
Synchronizing submodule url for 'meta-gigablue'
Synchronizing submodule url for 'meta-miraclebox'
Synchronizing submodule url for 'meta-openembedded'
Synchronizing submodule url for 'meta-qt5'
Synchronizing submodule url for 'meta-qviart'
Synchronizing submodule url for 'meta-sab'
Synchronizing submodule url for 'meta-spycat'
Synchronizing submodule url for 'meta-vuplus'
Synchronizing submodule url for 'meta-xp'
Synchronizing submodule url for 'meta-xpeedc'
Synchronizing submodule url for 'meta-xsarius.pli5'
Synchronizing submodule url for 'meta-xtrend'
Synchronizing submodule url for 'meta-zgemma'
Synchronizing submodule url for 'openembedded-core'
The openpli OE is now up-to-date.

Updated.

Compiling Dreambox images, please wait ...

Building image for dm500hd
ERROR: Traceback (most recent call last):
  File "/home/hjstrandby/openpli-oe-core/bitbake/lib/bb/cookerdata.py", line 184, in wrapped
    return func(fn, *args)
  File "/home/hjstrandby/openpli-oe-core/bitbake/lib/bb/cookerdata.py", line 209, in parse_config_file
    return bb.parse.handle(fn, data, include)
  File "/home/hjstrandby/openpli-oe-core/bitbake/lib/bb/parse/__init__.py", line 113, in handle
    return h['handle'](fn, data, include)
  File "/home/hjstrandby/openpli-oe-core/bitbake/lib/bb/parse/parse_py/ConfHandler.py", line 126, in handle
    abs_fn = resolve_file(fn, data)
  File "/home/hjstrandby/openpli-oe-core/bitbake/lib/bb/parse/__init__.py", line 136, in resolve_file
    raise IOError(errno.ENOENT, "file %s not found" % fn)
FileNotFoundError: [Errno 2] file /home/hjstrandby/openpli-oe-core/openvision-oe/meta-fulan/conf/layer.conf not found

**Comment by persianpros** [comment]
You just need to wait.
