### ISSUE TITLE
here is one problem

### ISSUE THREAD

**Issue by GM-990** [OpenVisionE2/openvision-oe#81]
``Initialising tasks: 100% |#############################################################################################################################| Time: 0:00:17
NOTE: Executing SetScene Tasks
ERROR: enigma2-alliance-plugins-gitAUTOINC+4d5f0faabb-r0 do_packagedata_setscene: The recipe enigma2-alliance-plugins is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
  /media/tas/linux/openpli-oe-core/build/tmp/pkgdata/spark/runtime/enigma2-plugin-extensions-remotechannelstreamconverter-src
    (matched in manifest-spark-enigma2-plugin-extensions-remotestreamconvert.packagedata)                                                                             
  /media/tas/linux/openpli-oe-core/build/tmp/pkgdata/spark/runtime/enigma2-plugin-extensions-remotechannelstreamconverter-src.packaged                                
    (matched in manifest-spark-enigma2-plugin-extensions-remotestreamconvert.packagedata)                                                                             
Please verify which recipe should provide the above files.                                                                                                            

The build has stopped, as continuing in this scenario WILL break things - if not now, possibly in the future (we've seen builds fail several months later). If the system knew how to recover from this automatically it would, however there are several different scenarios which can result in this and we don't know which one this is. It may be you have switched providers of something like virtual/kernel (e.g. from linux-yocto to linux-yocto-dev), in that case you need to execute the clean task for both recipes and it will resolve this error. It may be you changed DISTRO_FEATURES from systemd to udev or vice versa. Cleaning those recipes should again resolve this error, however switching DISTRO_FEATURES on an existing build directory is not supported - you should really clean out tmp and rebuild (reusing sstate should be safe). It could be the overlapping files detected are harmless in which case adding them to SSTATE_DUPWHITELIST may be the correct solution. It could also be your build is including two different conflicting versions of things (e.g. bluez 4 and bluez 5 and the correct solution for that would be to resolve the conflict. If in doubt, please ask on the mailing list, sharing the error and filelist above.                                                                                                 
ERROR: enigma2-alliance-plugins-gitAUTOINC+4d5f0faabb-r0 do_packagedata_setscene: If the above message is too much, the simpler version is you're advised to wipe out tmp and rebuild (reusing sstate is fine). That will likely fix things in most (but not all) cases.                                                                    
WARNING: Logfile for failed setscene task is /media/tas/linux/openpli-oe-core/build/tmp/work/spark-oe-linux/enigma2-alliance-plugins/gitAUTOINC+4d5f0faabb-r0/temp/log.do_packagedata_setscene.32152
WARNING: Setscene task (/media/tas/linux/openpli-oe-core/openvision-oe/recipes-openvision/enigma2-plugins/enigma2-alliance-plugins.bb:do_packagedata_setscene) failed with exit code '1' - real task will be run instead
NOTE: Executing RunQueue Tasks
ERROR: enigma2-alliance-plugins-gitAUTOINC+4d5f0faabb-r0 do_packagedata: The recipe enigma2-alliance-plugins is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
  /media/tas/linux/openpli-oe-core/build/tmp/pkgdata/spark/runtime/enigma2-plugin-extensions-remotechannelstreamconverter-src
    (matched in manifest-spark-enigma2-plugin-extensions-remotestreamconvert.packagedata)
  /media/tas/linux/openpli-oe-core/build/tmp/pkgdata/spark/runtime/enigma2-plugin-extensions-remotechannelstreamconverter-src.packaged
    (matched in manifest-spark-enigma2-plugin-extensions-remotestreamconvert.packagedata)
Please verify which recipe should provide the above files.

The build has stopped, as continuing in this scenario WILL break things - if not now, possibly in the future (we've seen builds fail several months later). If the system knew how to recover from this automatically it would, however there are several different scenarios which can result in this and we don't know which one this is. It may be you have switched providers of something like virtual/kernel (e.g. from linux-yocto to linux-yocto-dev), in that case you need to execute the clean task for both recipes and it will resolve this error. It may be you changed DISTRO_FEATURES from systemd to udev or vice versa. Cleaning those recipes should again resolve this error, however switching DISTRO_FEATURES on an existing build directory is not supported - you should really clean out tmp and rebuild (reusing sstate should be safe). It could be the overlapping files detected are harmless in which case adding them to SSTATE_DUPWHITELIST may be the correct solution. It could also be your build is including two different conflicting versions of things (e.g. bluez 4 and bluez 5 and the correct solution for that would be to resolve the conflict. If in doubt, please ask on the mailing list, sharing the error and filelist above.
ERROR: enigma2-alliance-plugins-gitAUTOINC+4d5f0faabb-r0 do_packagedata: If the above message is too much, the simpler version is you're advised to wipe out tmp and rebuild (reusing sstate is fine). That will likely fix things in most (but not all) cases.
ERROR: enigma2-alliance-plugins-gitAUTOINC+4d5f0faabb-r0 do_packagedata: Function failed: sstate_task_postfunc
ERROR: Logfile of failure stored in: /media/tas/linux/openpli-oe-core/build/tmp/work/spark-oe-linux/enigma2-alliance-plugins/gitAUTOINC+4d5f0faabb-r0/temp/log.do_packagedata.32187
ERROR: Task (/media/tas/linux/openpli-oe-core/openvision-oe/recipes-openvision/enigma2-plugins/enigma2-alliance-plugins.bb:do_packagedata) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5134 tasks of which 5133 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /media/tas/linux/openpli-oe-core/openvision-oe/recipes-openvision/enigma2-plugins/enigma2-alliance-plugins.bb:do_packagedata

**Comment by persianpros** [comment]
Please test and report now :+1:

**Comment by GM-990** [comment]
ok  thank 
build  succeeded.
