### ISSUE TITLE
DM 800

### ISSUE THREAD

**Issue by elhawaryna** [OpenVisionE2/openvision-oe#82]
./image.sh: 63: [: MACHINE=dm800: unexpected operator
./image.sh: 73: [: MACHINE=dm800: unexpected operator
./image.sh: 80: [: MACHINE=dm800: unexpected operator
./image.sh: 85: [: MACHINE=dm800: unexpected operator
./image.sh: 91: [: MACHINE=dm800: unexpected operator
./image.sh: 96: [: MACHINE=dm800: unexpected operator
./image.sh: 103: [: MACHINE=dm800: unexpected operator
./image.sh: 122: [: MACHINE=dm800: unexpected operator
./image.sh: 126: [: MACHINE=dm800: unexpected operator
./image.sh: 130: [: MACHINE=dm800: unexpected operator
Can not create image

**Comment by persianpros** [comment]
As you could read in our forum and https://github.com/OpenVisionE2/openvision-oe/issues/83 :

- Do we provide support for self-building? No! We prefer to work on our projects.

We don't have problem with this so there's no problem.

**Comment by elhawaryna** [comment]
OK
But there is no picture of the Dreambox to download
Is support for these devices stopped?
ٍ
My sincere respect
________________________________

**Comment by persianpros** [comment]
No don't worry we're compiling and uploading r7 ;)

**Comment by elhawaryna** [comment]
Thank you very much
________________________________
