### ISSUE TITLE
sh4 problems error when building

### ISSUE THREAD

**Issue by backup1977** [OpenVisionE2/openvision-oe#85]
Hello ...

I'm having trouble building errors since this commit:
https://github.com/OpenVisionE2/openvision-oe/commit/349bbdba6c55d0f47e3aef1f76c8a0f4cd251298

I get this error but only if I build the image without wifi driver. I then tried to build with wifi driver, and it works without error

this line is inserted in the cuberevo.inc
require conf / machine / include / wifi-fulan.inc

Quote: I can not build an image without wifi driver now
and it only builds with wifi driver.

ERROR: openvision-enigma2-image-1.0-r0 do_rootfs: Unable to install packages. Command '/home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo-oe-linux/openvision-enigma2-image/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo-oe-linux/openvision-enigma2-image/1.0-r0/opkg.conf -t /home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo-oe-linux/openvision-enigma2-image/1.0-r0/temp/ipktemp/ -o /home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo-oe-linux/openvision-enigma2-image/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version   install busybox-cron modutils-loadscript enigma2-plugin-extensions-foreca sdparm rtl8192eu libavahi-client3 dropbear enigma2-plugin-systemplugins-osdpositionsetup libbluray kernel-module-rt2500usb firmware-rtl8712u enigma2-plugin-extensions-vlcplayer enigma2-plugin-extensions-blurayplayer enigma2-plugin-systemplugins-cablescan enigma2-plugin-systemplugins-positionersetup firmware-rtl8192cu volatile-media fakelocale avahi-daemon firmware-rt2870 enigma2-plugin-extensions-pictureplayer e2fsprogs-e2fsck python-ipaddress enigma2-plugin-softcams-oscam-emu openvision-version-info enigma2-plugin-systemplugins-hdmicec firmware-htc9271 enigma2-plugin-systemplugins-bh-skin-support enigma2-plugin-extensions-e2iplayer-deps enigma2-plugin-systemplugins-wirelesslan glibc-binary-localedata-en-gb kernel-module-rtl8187 firmware-rt73 python-imaging rtl8188eu kernel-module-rt73usb curl settings-autorestore enigma2-plugin-systemplugins-videotune enigma2-plugin-extensions-moviecut enigma2-plugin-extensions-xmodem run-postinsts firmware-carl9170 kernel-module-block2mtd firmware-zd1211 enigma2-plugin-extensions-graphmultiepg enigma2-plugin-systemplugins-fastscan enigma2-plugin-extensions-audiosync enigma2 ca-certificates packagegroup-base enigma2-plugin-systemplugins-hotplug vsftpd packagegroup-core-boot python-netifaces enigma2-plugin-extensions-backupsuite enigma2-plugin-systemplugins-skinselector libcrypto1.0.2 samba-base python-pysmb e2fsprogs-mke2fs openssh-sftp wscan enigma2-plugin-systemplugins-satfinder wget tuxbox-common enigma2-plugin-systemplugins-systemtime enigma2-plugin-extensions-openwebif-extras enigma2-plugin-systemplugins-softwaremanager enigma2-plugin-extensions-cacheflush firmware-rtl8192eu hddtemp enigma2-plugin-systemplugins-networkbrowser enigma2-plugin-extensions-e2iplayer enigma2-plugin-extensions-filebrowser enigma2-plugin-extensions-cutlisteditor distro-feed-configs dvbsnoop tzdata ntp enigma2-plugin-extensions-reconstructapsc nfs-utils-client ntfs-3g fuse-exfat firmware-htc7010 enigma2-plugin-systemplugins-commoninterfaceassignment kernel-module-rt2800usb parted opkg kernel-params astra-sm enigma2-plugin-extensions-mediascanner enigma2-plugin-systemplugins-osd3dsetup e2fsprogs-tune2fs enigma2-plugin-extensions-mediaplayer aio-grab openssh-sftp-server firmware-rtl8188eu enigma2-plugin-systemplugins-videoenhancement enigma2-plugin-softcams-oscam enigma2-plugin-extensions-autobackup enigma2-plugin-systemplugins-videomode openvision-bootlogo nfs-utils enigma2-plugin-extensions-dlnabrowser kernel-module-zd1211rw openvision-module enigma2-plugin-extensions-openwebif-extras-terminal enigma2-plugin-systemplugins-setpasswd' returned 255:
Collected errors:
 * opkg_prepare_url_for_install: Couldn't find anything to satisfy 'kernel-module-rt2500usb'.
 * rm_r: Failed to open dir /home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo-oe-linux/openvision-enigma2-image/1.0-r0/temp/ipktemp//opkg-rQP04Q: No such file or directory.

ERROR: openvision-enigma2-image-1.0-r0 do_rootfs: Function failed: do_rootfs
ERROR: Logfile of failure stored in: /home/ghani/openvision/openpli-oe-core/build/tmp/work/cuberevo-oe-linux/openvision-enigma2-image/1.0-r0/temp/log.do_rootfs.29467
ERROR: Task (/home/ghani/openvision/openpli-oe-core/openvision-oe/recipes-openvision/images/openvision-enigma2-image.bb:do_rootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 6866 tasks of which 4877 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/ghani/openvision/openpli-oe-core/openvision-oe/recipes-openvision/images/openvision-enigma2-image.bb:do_rootfs
Summary: There were 22 WARNING messages shown.
Summary: There were 276 ERROR messages shown, returning a non-zero exit code.
Makefile:125: die Regel für Ziel „image“ scheiterte
make: *** [image] Fehler 1

**Comment by persianpros** [comment]
If our build is ok it means everything is ok, anything else is not our responsibility: https://github.com/OpenVisionE2/openvision-oe#support

- Do we provide support for self-building? No! We prefer to work on our projects.

Sorry but this is our policy.
