### ISSUE TITLE
arithmetic syntax error in backup suite at line 571

### ISSUE THREAD

**Issue by shmoxy75** [OpenVisionE2/openvision-oe#9]
I got it finaly and installed the image on dm520 it works well but in backupsuite a got this message error when i try to backup image on usb stick

/usr/lib/enigma2/pythonPlugins/Extensions/BackupSuite/backupdmm.sh line 571 
arithmetic syntax error

**Comment by persianpros** [comment]
You need to post this in https://github.com/OpenVisionE2/BackupSuite/issues

**Comment by moksy386** [comment]
Okay done thanks
